// <auto-generated/>
// This file was generated by Wireloom from '13-alias-inheritance.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusIntegrationTrace;

/// <summary>
/// Represents the <c>Base</c> DDS type declared in <c>13-alias-inheritance.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Base : global::System.IEquatable<Base>
{
    /// <summary>
    /// Gets or sets the <c>baseValue</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>.
    /// </summary>
    public int baseValue { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Base"/> class.
    /// </summary>
    public Base()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Base"/> class with the supplied member values.
    /// </summary>
    /// <param name="baseValue">The value for the <c>baseValue</c> member.</param>
    public Base(int baseValue)
    {
        this.baseValue = baseValue;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Base"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Base();
    /// var copy = new Base(original);
    /// </code>
    /// </example>
    public Base(Base? other)
    {
        if (other is null)
        {
            return;
        }

        baseValue = other.baseValue;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(baseValue);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Base? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return baseValue.Equals(other.baseValue);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Base);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => BaseSupport.Instance.ToString(this);
}
