// <auto-generated/>
// This file was generated by Wireloom from '13-alias-inheritance.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusIntegrationTrace.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Derived"/>.
/// </summary>
public struct DerivedUnmanaged : INativeTopicType<Derived>
{
    private BaseUnmanaged parent;
    private NativeString state;
    private ContextUnmanaged traceContext;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        parent.Destroy(optionalsOnly);
        traceContext.Destroy(optionalsOnly);

        if (optionalsOnly)
        {
            return;
        }

        state.Destroy();
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Derived sample, bool keysOnly = false)
    {
        parent.FromNative(sample, keysOnly);
        sample.state = state.FromNative();
        traceContext.FromNative(sample.traceContext, keysOnly: false);
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        parent.Initialize(allocatePointers, allocateMemory);
        state.Initialize(size: 16, allocateMemory: allocateMemory);
        traceContext.Initialize(allocatePointers, allocateMemory);
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Derived sample, bool keysOnly = false)
    {
        parent.ToNative(sample, keysOnly);
        state.ToNative(sample.state, 16);
        traceContext.ToNative(sample.traceContext, keysOnly: false);
    }
}
