// <auto-generated/>
// This file was generated by Wireloom from '13-alias-inheritance.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusIntegrationTrace;

/// <summary>
/// Represents the <c>Context</c> DDS type declared in <c>13-alias-inheritance.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Context : global::System.IEquatable<Context>
{
    /// <summary>
    /// Gets or sets the <c>correlation</c> member. Its maximum length is <c>32</c> UTF-8 bytes.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this narrow IDL string is measured in UTF-8 bytes. The generated C# property does not check the bound when assigned.</remarks>
    [Bound(32)]
    public string correlation { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the <c>producer</c> member. This member is optional. Its maximum length is <c>16</c> UTF-8 bytes. A null value means the member is absent.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this narrow IDL string is measured in UTF-8 bytes. The generated C# property does not check the bound when assigned.</remarks>
    /// <example>
    /// <code>
    /// var sample = new Context();
    /// sample.producer = null; // the member is absent
    /// </code>
    /// </example>
    [Optional]
    [Bound(16)]
    public string? producer { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Context"/> class.
    /// </summary>
    public Context()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Context"/> class with the supplied member values.
    /// </summary>
    /// <param name="correlation">The value for the <c>correlation</c> member.</param>
    /// <param name="producer">The value for the <c>producer</c> member.</param>
    public Context(string correlation, string? producer)
    {
        this.correlation = correlation;
        this.producer = producer;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Context"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Context();
    /// var copy = new Context(original);
    /// </code>
    /// </example>
    public Context(Context? other)
    {
        if (other is null)
        {
            return;
        }

        correlation = other.correlation;
        producer = other.producer;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(correlation);
        hash.Add(producer);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Context? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return correlation.Equals(other.correlation)
            && Equals(producer, other.producer);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Context);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => ContextSupport.Instance.ToString(this);
}
