// <auto-generated/>
// This file was generated by Wireloom from '13-alias-inheritance.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusIntegrationTrace;

/// <summary>
/// Represents the <c>Producer</c> IDL typedef declared in <c>13-alias-inheritance.idl</c>.
/// </summary>
public partial class Producer : global::System.IEquatable<Producer>
{
    /// <summary>
    /// Gets or sets the value represented by this typedef. Its IDL bound is <c>16</c> characters.
    /// </summary>
    /// <remarks>The bound on this narrow IDL string counts characters. RTI encodes narrow IDL strings as UTF-8 by default. The generated C# property does not check the bound when assigned.</remarks>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    [Bound(16)]
    public string Value { get; set; } = string.Empty;

    /// <summary>
    /// Initializes the typedef value to its default value.
    /// </summary>
    public Producer()
    {
    }

    /// <summary>
    /// Initializes the typedef with a value.
    /// </summary>
    /// <param name="Value">The value to store.</param>
    /// <remarks>The constructor stores the supplied reference as provided; it does not make a copy.</remarks>
    public Producer(string Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another typedef value.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor returns without copying and keeps its property initializer. An aggregate value is copied through its generated copy constructor.</remarks>
    public Producer(Producer? other)
    {
        if (other is not null)
        {
            Value = other.Value;
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(Value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    /// <returns><see langword="true"/> when both typedefs have equal values; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Producer? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Producer);

    /// <summary>
    /// Formats this typedef as readable text.
    /// </summary>
    /// <returns>A readable string formatted by this typedef's type-support instance.</returns>
    public override string ToString() => ProducerSupport.Instance.ToString(this);
}
