// <auto-generated/>
// This file was generated by Wireloom from '13-alias-inheritance.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusIntegrationTrace;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Producer"/>.
/// </summary>
public class ProducerSupport : TypeSupport<Producer>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ProducerSupport"/> class.
    /// </summary>
    public ProducerSupport() : base(
        new Implementation.ProducerPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.ProducerPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for formatting, serialization, and dynamic-type utilities for this typedef.
    /// </summary>
    /// <remarks>The generated plugin and unmanaged type are runtime implementation details; application code should use this support class and the managed typedef.</remarks>
    public static ProducerSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ProducerSupport, Producer>();
}
