// <auto-generated/>
// This file was generated by Wireloom from '13-alias-inheritance.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusIntegrationTrace;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Base"/>.
/// </summary>
public class BaseSupport : TypeSupport<Base>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="BaseSupport"/> class.
    /// </summary>
    public BaseSupport() : base(
        new Implementation.BasePlugin(),
        new Lazy<DynamicType>(() => Implementation.BasePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static BaseSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<BaseSupport, Base>();
}
