// <auto-generated/>
// This file was generated by Wireloom from '13-alias-inheritance.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusIntegrationTrace.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Context"/>.
/// </summary>
public struct ContextUnmanaged : INativeTopicType<Context>
{
    private NativeString correlation;
    private NativeString producer;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        producer.Destroy();

        if (optionalsOnly)
        {
            return;
        }

        correlation.Destroy();
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Context sample, bool keysOnly = false)
    {
        sample.correlation = correlation.FromNative();
        sample.producer = producer.FromNativeOptional();
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        correlation.Initialize(size: 32, allocateMemory: allocateMemory);
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Context sample, bool keysOnly = false)
    {
        correlation.ToNative(sample.correlation, 32);
        producer.ToNativeOptional(sample.producer, 16);
    }
}
