// <auto-generated/>
// This file was generated by Wireloom from '13-compositions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusIntegrationCollections;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>13-compositions.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Sample : IEquatable<Sample>
{
    /// <summary>
    /// Gets the <c>unboundedItems</c> member. Its maximum number of elements is <c>100</c>.
    /// </summary>
    [Bound(100)]
    public ISequence<Item> unboundedItems { get; } = null!;

    /// <summary>
    /// Gets the <c>boundedItems</c> member. Its maximum number of elements is <c>2</c>.
    /// </summary>
    [Bound(2)]
    public ISequence<Item> boundedItems { get; } = null!;

    /// <summary>
    /// Gets or sets the <c>aggregateArray</c> member.
    /// </summary>
    public Item[] aggregateArray { get; set; } = null!;

    /// <summary>
    /// Gets or sets the <c>rows</c> member.
    /// </summary>
    public Row[] rows { get; set; } = null!;

    /// <summary>
    /// Gets the <c>sequenceOfArrays</c> member. Its maximum number of elements is <c>2</c>.
    /// </summary>
    [Bound(2)]
    public ISequence<Row> sequenceOfArrays { get; } = null!;

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
        unboundedItems = new Sequence<Item>();
        boundedItems = new Sequence<Item>();
        sequenceOfArrays = new Sequence<Row>();
        aggregateArray = new Item[2];

        for (var dimension0 = 0; dimension0 < 2; dimension0++)
        {
            aggregateArray[dimension0] = new Item();
        }

        rows = new Row[2];

        for (var dimension0 = 0; dimension0 < 2; dimension0++)
        {
            rows[dimension0] = new Row();
        }
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="unboundedItems">The value for the <c>unboundedItems</c> member.</param>
    /// <param name="boundedItems">The value for the <c>boundedItems</c> member.</param>
    /// <param name="aggregateArray">The value for the <c>aggregateArray</c> member.</param>
    /// <param name="rows">The value for the <c>rows</c> member.</param>
    /// <param name="sequenceOfArrays">The value for the <c>sequenceOfArrays</c> member.</param>
    public Sample(ISequence<Item> unboundedItems, ISequence<Item> boundedItems, Item[] aggregateArray, Row[] rows, ISequence<Row> sequenceOfArrays)
    {
        this.unboundedItems = unboundedItems;
        this.boundedItems = boundedItems;
        this.aggregateArray = aggregateArray;
        this.rows = rows;
        this.sequenceOfArrays = sequenceOfArrays;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        unboundedItems = new Sequence<Item>(other.unboundedItems.Select(element => new Item(element)));
        boundedItems = new Sequence<Item>(other.boundedItems.Select(element => new Item(element)));
        aggregateArray = (Item[])other.aggregateArray.Clone();

        for (var dimension0 = 0; dimension0 < 2; dimension0++)
        {
            aggregateArray[dimension0] = new Item(other.aggregateArray[dimension0]);
        }

        rows = (Row[])other.rows.Clone();

        for (var dimension0 = 0; dimension0 < 2; dimension0++)
        {
            rows[dimension0] = new Row(other.rows[dimension0]);
        }

        sequenceOfArrays = new Sequence<Row>(other.sequenceOfArrays.Select(element => new Row(element)));
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(unboundedItems.Count);
        hash.Add(boundedItems.Count);
        hash.Add(aggregateArray[0]);
        hash.Add(rows[0]);
        hash.Add(sequenceOfArrays.Count);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return unboundedItems.SequenceEqual(other.unboundedItems)
            && boundedItems.SequenceEqual(other.boundedItems)
            && aggregateArray.Cast<Item>().SequenceEqual(other.aggregateArray.Cast<Item>())
            && rows.Cast<Row>().SequenceEqual(other.rows.Cast<Row>())
            && sequenceOfArrays.SequenceEqual(other.sequenceOfArrays);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
