// <auto-generated/>
// This file was generated by Wireloom from '13-compositions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusIntegrationCollections;

/// <summary>
/// Represents the <c>Row</c> IDL typedef declared in <c>13-compositions.idl</c>.
/// </summary>
public partial class Row : IEquatable<Row>
{
    /// <summary>
    /// Gets or sets the array value represented by this typedef.
    /// </summary>
    public int[] Value { get; set; } = new int[2];

    /// <summary>
    /// Initializes an empty array typedef.
    /// </summary>
    public Row()
    {
    }

    /// <summary>
    /// Initializes the typedef with an array value.
    /// </summary>
    /// <param name="Value">The array value to store.</param>
    public Row(int[] Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another array typedef.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    public Row(Row? other)
    {
        if (other is null)
        {
            return;
        }

        Value = (int[])other.Value.Clone();
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Value.Cast<int>().First().GetHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same array values as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    public bool Equals(Row? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Rank == other.Value.Rank
            && Value.Cast<int>().SequenceEqual(other.Value.Cast<int>());
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Row);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this typedef.
    /// </summary>
    public override string ToString() => RowSupport.Instance.ToString(this);
}
