// <auto-generated/>
// This file was generated by Wireloom from '13-compositions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusIntegrationCollections;

/// <summary>
/// Represents the <c>Row</c> IDL typedef declared in <c>13-compositions.idl</c>.
/// </summary>
public partial class Row : global::System.IEquatable<Row>
{
    /// <summary>
    /// Gets or sets the array value represented by this typedef.
    /// </summary>
    public int[] Value { get; set; } = new int[2];

    /// <summary>
    /// Initializes a fixed-size array typedef with dimensions 2 (2 elements); each element starts at its default value.
    /// </summary>
    public Row()
    {
    }

    /// <summary>
    /// Initializes the typedef with an array value.
    /// </summary>
    /// <param name="Value">The array value to store.</param>
    /// <remarks>The typedef stores the supplied array reference; it does not make a copy.</remarks>
    public Row(int[] Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another array typedef.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    /// <remarks>The constructor creates a new array container. When <paramref name="other"/> is null, the initially allocated array remains in place.</remarks>
    public Row(Row? other)
    {
        if (other is null)
        {
            return;
        }

        Value = (int[])other.Value.Clone();
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(Value[0]);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same array values as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    /// <returns><see langword="true"/> when both arrays have the same dimensions and equal values; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Row? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return global::System.Linq.Enumerable.SequenceEqual(Value, other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Row);

    /// <summary>
    /// Formats this typedef as readable text.
    /// </summary>
    /// <returns>A readable string formatted by this typedef's type-support instance.</returns>
    public override string ToString() => RowSupport.Instance.ToString(this);
}
