// <auto-generated/>
// This file was generated by Wireloom from '13-compositions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusIntegrationCollections.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Sample"/>.
/// </summary>
internal class SamplePlugin : InterpretedTypePlugin<Sample, SampleUnmanaged>
{
    internal SamplePlugin() : base("CorpusIntegrationCollections.Sample", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Sample"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("unboundedItems", tsf.CreateSequenceWithAccessInfo(dtf, ItemSupport.Instance.GetDynamicTypeInternal(isPublic), 100), id: 0),
            new StructMember("boundedItems", tsf.CreateSequenceWithAccessInfo(dtf, ItemSupport.Instance.GetDynamicTypeInternal(isPublic), 2), id: 1),
            new StructMember("aggregateArray", tsf.CreateArrayWithAccessInfo<ItemUnmanaged>(dtf, ItemSupport.Instance.GetDynamicTypeInternal(isPublic), new uint[] { 2 }), id: 2),
            new StructMember("rows", tsf.CreateArrayWithAccessInfo<RowUnmanaged>(dtf, RowSupport.Instance.GetDynamicTypeInternal(isPublic), new uint[] { 2 }), id: 3),
            new StructMember("sequenceOfArrays", tsf.CreateSequenceWithAccessInfo(dtf, RowSupport.Instance.GetDynamicTypeInternal(isPublic), 2), id: 4)
        };

        var result = tsf.CreateTypeWithAccessInfo<SampleUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusIntegrationCollections::Sample")
                .AddMembers(members));

        return result;
    }
}
