// <auto-generated/>
// This file was generated by Wireloom from '07-union-enum.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusEnumUnion;

/// <summary>
/// Represents the <c>Kind</c> enumeration declared in <c>07-union-enum.idl</c>.
/// </summary>
public enum Kind
{
    /// <summary>
    /// The <c>Number</c> enumeration value.
    /// </summary>
    Number,

    /// <summary>
    /// The <c>Text</c> enumeration value.
    /// </summary>
    Text,

    /// <summary>
    /// The <c>PayloadValue</c> enumeration value.
    /// </summary>
    PayloadValue,
}
