// <auto-generated/>
// This file was generated by Wireloom from '07-union-enum.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types.Dynamic;

namespace CorpusEnumUnion.Implementation;

/// <summary>
/// Provides the RTI runtime plugin for the <see cref="Kind"/> enumeration. This implementation detail is not intended for application code.
/// </summary>
internal class KindPlugin : EnumTypePlugin
{
    /// <summary>
    /// Initializes the RTI plugin for <see cref="Kind"/>.
    /// </summary>
    internal KindPlugin() : base(CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Kind"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    internal static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var enumType = dtf.BuildEnum()
            .WithName("CorpusEnumUnion::Kind")
            .AddMember(new EnumMember("Number", 0))
            .AddMember(new EnumMember("Text", 1))
            .AddMember(new EnumMember("PayloadValue", 2))
            .WithExtensibility(ExtensibilityKind.Extensible)
            .Create();

        {
            var annotations = new Annotations(
                TypeKind.Enumeration,
                defaultValue: new AnnotationParameterValue { EnumValue = 0 },
                minValue: null,
                maxValue: null,
                unit: null);
            enumType.SetAnnotations(annotations);
        }
        return enumType;
    }
}
