// <auto-generated/>
// This file was generated by Wireloom from '07-union-enum.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusEnumUnion.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Payload"/>.
/// </summary>
internal class PayloadPlugin : InterpretedTypePlugin<Payload, PayloadUnmanaged>
{
    internal PayloadPlugin() : base("CorpusEnumUnion.Payload", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Payload"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("code", dtf.GetPrimitiveType<int>(), id: 0),
            new StructMember("label", dtf.CreateString(16), id: 1)
        };

        var result = tsf.CreateTypeWithAccessInfo<PayloadUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusEnumUnion::Payload")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.String,
                defaultValue: new AnnotationParameterValue { StringValue = "" },
                minValue: null,
                maxValue: null,
                unit: null);
            result.SetMemberAnnotations(1, annotations);
        }

        return result;
    }
}
