// <auto-generated/>
// This file was generated by Wireloom from '07-union-enum.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusEnumUnion;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Kind"/>.
/// </summary>
public class KindSupport : TypeSupport<Kind>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="KindSupport"/> class.
    /// </summary>
    public KindSupport() : base(
        new Implementation.KindPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.KindPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for this enumeration.
    /// </summary>
    public static KindSupport Instance { get; } = 
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<KindSupport, Kind>();
}
