// <auto-generated/>
// This file was generated by Wireloom from '07-union-enum.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusEnumUnion.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Choice"/>.
/// </summary>
public struct ChoiceUnmanaged : INativeTopicType<Choice>
{
    private CorpusEnumUnion.Kind _discriminator;

    private int number;
    private NativeString text;
    private PayloadUnmanaged payload;

    /// <summary>
    /// Releases native resources held by this union.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        text.Destroy();
    }

    /// <summary>
    /// Copies the active native union branch into a managed sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Choice sample, bool keysOnly = false)
    {
        switch (_discriminator)
        {
            case CorpusEnumUnion.Kind.Number:
                sample.number = number;
                break;
            case CorpusEnumUnion.Kind.Text:
                sample.text = text.FromNative();
                break;
            case CorpusEnumUnion.Kind.PayloadValue:
                payload.FromNative(sample.payload, keysOnly: false);
                break;
            default:
                break;
        }
    }

    /// <summary>
    /// Initializes this native union representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        _discriminator = Choice.DefaultDiscriminator;

        number = 0;
        text.Initialize(size: 255, allocateMemory: allocateMemory);

        payload.Initialize(allocatePointers, allocateMemory);
    }

    /// <summary>
    /// Copies the active managed union branch into native storage.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Choice sample, bool keysOnly = false)
    {
        _discriminator = sample.Discriminator;
        switch (_discriminator)
        {
            case CorpusEnumUnion.Kind.Number:
                number = sample.number;
                break;
            case CorpusEnumUnion.Kind.Text:
                text.ToNative(sample.text, 255);
                break;
            case CorpusEnumUnion.Kind.PayloadValue:
                payload.ToNative(sample.payload, keysOnly: false);
                break;
            default:
                break;
        }
    }
}
