// <auto-generated/>
// This file was generated by Wireloom from '07-union-enum.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusEnumUnion;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Choice"/>.
/// </summary>
public class ChoiceSupport : TypeSupport<Choice>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ChoiceSupport"/> class.
    /// </summary>
    public ChoiceSupport() : base(
        new Implementation.ChoicePlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.ChoicePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static ChoiceSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ChoiceSupport, Choice>();
}
