// <auto-generated/>
// This file was generated by Wireloom from '07-union-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusUnionAliases;

/// <summary>
/// Represents the <c>ChoiceAlias2</c> IDL typedef declared in <c>07-union-aliases.idl</c>.
/// </summary>
public partial class ChoiceAlias2 : global::System.IEquatable<ChoiceAlias2>
{
    /// <summary>
    /// Gets or sets the value represented by this typedef.
    /// </summary>
    public Choice Value { get; set; } = null!;

    /// <summary>
    /// Initializes the typedef value to its default value.
    /// </summary>
    public ChoiceAlias2()
    {
        Value = new Choice();
    }

    /// <summary>
    /// Initializes the typedef with a value.
    /// </summary>
    /// <param name="value">The value to store.</param>
    /// <remarks>The constructor stores the supplied reference as provided; it does not make a copy.</remarks>
    public ChoiceAlias2(Choice value)
    {
        Value = value;
    }

    /// <summary>
    /// Initializes a copy of another typedef value.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor returns without copying and keeps its property initializer. An aggregate value is copied through its generated copy constructor.</remarks>
    public ChoiceAlias2(ChoiceAlias2? other)
    {
        if (other is not null)
        {
            Value = new Choice(other.Value);
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(Value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    /// <returns><see langword="true"/> when both typedefs have equal values; otherwise, <see langword="false"/>.</returns>
    public bool Equals(ChoiceAlias2? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as ChoiceAlias2);

    /// <summary>
    /// Formats this typedef as readable text.
    /// </summary>
    /// <returns>A readable string formatted by this typedef's type-support instance.</returns>
    public override string ToString() => ChoiceAlias2Support.Instance.ToString(this);
}
