// <auto-generated/>
// This file was generated by Wireloom from '07-union-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusUnionAliases;

/// <summary>
/// Represents the <c>Kind</c> enumeration declared in <c>07-union-aliases.idl</c>.
/// </summary>
public enum Kind
{
    /// <summary>
    /// The <c>Zero</c> enumeration value.
    /// </summary>
    Zero = 0,

    /// <summary>
    /// The <c>Ten</c> enumeration value.
    /// </summary>
    Ten = 10,
}
