// <auto-generated/>
// This file was generated by Wireloom from '07-union-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusUnionAliases;

/// <summary>
/// Represents the <c>Choice</c> DDS union declared in <c>07-union-aliases.idl</c>. Exactly one branch is selected by <see cref="Discriminator"/>.
/// </summary>
public partial class Choice : IEquatable<Choice>
{
    private int _zero;
    private string _ten = string.Empty;

    /// <summary>
    /// Gets the discriminator that selects the active DDS union branch.
    /// </summary>
    public Kind Discriminator { get; private set; }

    /// <summary>
    /// Gets the discriminator value used to initialize this union.
    /// </summary>
    public const Kind DefaultDiscriminator = 0;

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>CorpusUnionAliases.Kind.Zero</c>.
    /// </summary>
    public int zero
    {
        get
        {
            if (Discriminator != Kind.Zero)
            {
                throw new InvalidOperationException("zero not selected");
            }

            return _zero;
        }
        set
        {
            _zero = value;

            Discriminator = Kind.Zero;
        }
    }

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>CorpusUnionAliases.Kind.Ten</c>.
    /// </summary>
    [Bound(255)]
    public string ten
    {
        get
        {
            if (Discriminator != Kind.Ten)
            {
                throw new InvalidOperationException("ten not selected");
            }

            return _ten;
        }
        set
        {
            _ten = value;

            Discriminator = Kind.Ten;
        }
    }

    /// <summary>
    /// Initializes a new union with its RTI default discriminator.
    /// </summary>
    public Choice()
    {
        Discriminator = DefaultDiscriminator;
    }

    /// <summary>
    /// Initializes a copy of another <see cref="Choice"/> union.
    /// </summary>
    /// <param name="other">The union to copy.</param>
    public Choice(Choice? other)
    {
        if (other is null)
        {
            return;
        }

        Discriminator = other.Discriminator;

        switch (Discriminator)
        {
            case Kind.Zero:
                this._zero = other.zero;
                break;
            case Kind.Ten:
                this._ten = other.ten;
                break;
            default:
                break;
        }
    }

    /// <summary>
    /// Gets the currently active union-branch value.
    /// </summary>
    /// <returns>The value of the branch selected by <see cref="Discriminator"/>.</returns>
    public object Get()
    {
        return Discriminator switch
        {
            Kind.Zero => zero,
            Kind.Ten => ten,
            _ => null,
        };
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Discriminator switch
        {
            Kind.Zero => HashCode.Combine(Discriminator, zero),
            Kind.Ten => HashCode.Combine(Discriminator, ten),
            _ => HashCode.Combine(Discriminator),
        };
    }

    /// <summary>
    /// Determines whether this union has the same discriminator and active branch value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The union to compare.</param>
    /// <returns><see langword="true"/> when both unions select equal values; otherwise <see langword="false"/>.</returns>
    public bool Equals(Choice? other)
    {
        if (other is null || Discriminator != other.Discriminator)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return Discriminator switch
        {
            Kind.Zero => zero.Equals(other.zero),
            Kind.Ten => ten.Equals(other.ten),
            _ => true,
        };
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Choice);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this union.
    /// </summary>
    public override string ToString() => ChoiceSupport.Instance.ToString(this);
}
