// <auto-generated/>
// This file was generated by Wireloom from '07-union-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusUnionAliases;

/// <summary>
/// Represents the <c>Choice</c> DDS union declared in <c>07-union-aliases.idl</c>. The discriminator selects a branch when it matches a declared label; otherwise, no branch is active.
/// </summary>
public partial class Choice : global::System.IEquatable<Choice>
{
    private int _zero;
    private string _ten = string.Empty;

    /// <summary>
    /// Gets the discriminator that selects the active DDS union branch.
    /// </summary>
    public Kind Discriminator { get; private set; }

    /// <summary>
    /// Gets the discriminator value used by the parameterless constructor.
    /// </summary>
    public const Kind DefaultDiscriminator = (Kind)0;

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>Kind.Zero</c>.
    /// </summary>
    /// <remarks>Reading this property while another branch is active throws <see cref="global::System.InvalidOperationException"/>. Assigning it stores the value and changes <see cref="Discriminator"/> to a label for this branch.</remarks>
    /// <exception cref="global::System.InvalidOperationException">The discriminator selects another branch or selects no branch.</exception>
    public int zero
    {
        get
        {
            if (Discriminator != Kind.Zero)
            {
                throw new global::System.InvalidOperationException("zero not selected");
            }

            return _zero;
        }
        set
        {
            _zero = value;

            Discriminator = Kind.Zero;
        }
    }

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>Kind.Ten</c>.
    /// </summary>
    /// <remarks>Reading this property while another branch is active throws <see cref="global::System.InvalidOperationException"/>. Assigning it stores the value and changes <see cref="Discriminator"/> to a label for this branch.</remarks>
    /// <exception cref="global::System.InvalidOperationException">The discriminator selects another branch or selects no branch.</exception>
    [Bound(255)]
    public string ten
    {
        get
        {
            if (Discriminator != Kind.Ten)
            {
                throw new global::System.InvalidOperationException("ten not selected");
            }

            return _ten;
        }
        set
        {
            _ten = value;

            Discriminator = Kind.Ten;
        }
    }

    /// <summary>
    /// Initializes a new union with its RTI default discriminator. A branch is active only when that discriminator matches a declared label or selects the default branch.
    /// </summary>
    public Choice()
    {
        Discriminator = DefaultDiscriminator;
    }

    /// <summary>
    /// Initializes a copy of another <see cref="Choice"/> union.
    /// </summary>
    /// <param name="other">The union to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor leaves the discriminator at its default and does not copy a branch value.</remarks>
    public Choice(Choice? other)
    {
        if (other is null)
        {
            return;
        }

        Discriminator = other.Discriminator;

        switch (Discriminator)
        {
            case Kind.Zero:
                this._zero = other.zero;
                break;
            case Kind.Ten:
                this._ten = other.ten;
                break;
            default:
                break;
        }
    }

    /// <summary>
    /// Gets the value of the currently active union branch, if any.
    /// </summary>
    /// <returns>The concrete value of the active branch, or <see langword="null"/> when the discriminator selects no declared branch.</returns>
    public object? Get()
    {
        return Discriminator switch
        {
            Kind.Zero => zero,
            Kind.Ten => ten,
            _ => null,
        };
    }

    /// <summary>
    /// Computes a hash from the discriminator and, when a branch is active, its value.
    /// </summary>
    public override int GetHashCode()
    {
        return Discriminator switch
        {
            Kind.Zero => global::System.HashCode.Combine(Discriminator, zero),
            Kind.Ten => global::System.HashCode.Combine(Discriminator, ten),
            _ => global::System.HashCode.Combine(Discriminator),
        };
    }

    /// <summary>
    /// Determines whether this union has the same discriminator and active branch value as <paramref name="other"/>. When neither discriminator selects a branch, equality depends on the discriminator alone.
    /// </summary>
    /// <param name="other">The union to compare.</param>
    /// <returns><see langword="true"/> when both unions select equal values; otherwise <see langword="false"/>.</returns>
    public bool Equals(Choice? other)
    {
        if (other is null || Discriminator != other.Discriminator)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Discriminator switch
        {
            Kind.Zero => zero.Equals(other.zero),
            Kind.Ten => ten.Equals(other.ten),
            _ => true,
        };
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Choice);

    /// <summary>
    /// Formats this union as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the union's type-support instance.</returns>
    public override string ToString() => ChoiceSupport.Instance.ToString(this);
}
