// <auto-generated/>
// This file was generated by Wireloom from '02-scopes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusScopes;

/// <summary>
/// Represents the <c>KeywordRecord</c> DDS type declared in <c>02-scopes.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class KeywordRecord : IEquatable<KeywordRecord>
{
    /// <summary>
    /// Gets or sets the <c>event</c> member.
    /// </summary>
    public int @event { get; set; }

    /// <summary>
    /// Gets or sets the <c>relative</c> member.
    /// </summary>
    public Nested.Point relative { get; set; } = new Nested.Point();

    /// <summary>
    /// Gets or sets the <c>absolute</c> member.
    /// </summary>
    public Nested.Point absolute { get; set; } = new Nested.Point();

    /// <summary>
    /// Gets the <c>values</c> member. Its maximum number of elements is <c>4</c>.
    /// </summary>
    [Bound(4)]
    public ISequence<int> values { get; } = null!;

    /// <summary>
    /// Initializes a new instance of the <see cref="KeywordRecord"/> class.
    /// </summary>
    public KeywordRecord()
    {
        values = new Sequence<int>();
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="KeywordRecord"/> class with the supplied member values.
    /// </summary>
    /// <param name="@event">The value for the <c>event</c> member.</param>
    /// <param name="relative">The value for the <c>relative</c> member.</param>
    /// <param name="absolute">The value for the <c>absolute</c> member.</param>
    /// <param name="values">The value for the <c>values</c> member.</param>
    public KeywordRecord(int @event, Nested.Point relative, Nested.Point absolute, ISequence<int> values)
    {
        this.@event = @event;
        this.relative = relative;
        this.absolute = absolute;
        this.values = values;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="KeywordRecord"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public KeywordRecord(KeywordRecord? other)
    {
        if (other is null)
        {
            return;
        }

        @event = other.@event;
        relative = new Nested.Point(other.relative);
        absolute = new Nested.Point(other.absolute);
        values = new Sequence<int>(other.values);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(@event);
        hash.Add(relative);
        hash.Add(absolute);
        hash.Add(values.Count);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(KeywordRecord? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return @event.Equals(other.@event)
            && relative.Equals(other.relative)
            && absolute.Equals(other.absolute)
            && values.SequenceEqual(other.values);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as KeywordRecord);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => KeywordRecordSupport.Instance.ToString(this);
}
