// <auto-generated/>
// This file was generated by Wireloom from '02-scopes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusScopes;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Reopened"/>.
/// </summary>
public class ReopenedSupport : TypeSupport<Reopened>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ReopenedSupport"/> class.
    /// </summary>
    public ReopenedSupport() : base(
        new Implementation.ReopenedPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.ReopenedPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static ReopenedSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ReopenedSupport, Reopened>();
}
