// <auto-generated/>
// This file was generated by Wireloom from '02-scopes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusScopes;

/// <summary>
/// Represents the <c>Reopened</c> DDS type declared in <c>02-scopes.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Reopened : global::System.IEquatable<Reopened>
{
    /// <summary>
    /// Gets or sets the <c>value</c> member.
    /// </summary>
    public KeywordRecord value { get; set; } = new KeywordRecord();

    /// <summary>
    /// Initializes a new instance of the <see cref="Reopened"/> class.
    /// </summary>
    /// <remarks>nested aggregate members start as new instances.</remarks>
    public Reopened()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Reopened"/> class with the supplied member values.
    /// </summary>
    /// <param name="value">The value for the <c>value</c> member.</param>
    /// <remarks>The constructor stores supplied reference-type member values as provided. It does not clone their arrays, sequences, or nested objects.</remarks>
    public Reopened(KeywordRecord value)
    {
        this.value = value;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Reopened"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Reopened();
    /// var copy = new Reopened(original);
    /// </code>
    /// </example>
    public Reopened(Reopened? other)
    {
        if (other is null)
        {
            return;
        }

        value = new KeywordRecord(other.value);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Reopened? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return value.Equals(other.value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Reopened);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => ReopenedSupport.Instance.ToString(this);
}
