// <auto-generated/>
// This file was generated by Wireloom from '03-alias-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusCollectionAliases.Implementation;

internal class NestedSequencePlugin : InterpretedTypePlugin<NestedSequence, NestedSequenceUnmanaged>
{
    internal NestedSequencePlugin() : base("CorpusCollectionAliases.NestedSequence", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="NestedSequence"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        return tsf.CreateAliasWithAccessInfo<NestedSequenceUnmanaged>(dtf, "NestedSequence", tsf.CreateSequenceWithAccessInfo(dtf, LongSequenceSupport.Instance.GetDynamicTypeInternal(isPublic), 2));
    }
}
