// <auto-generated/>
// This file was generated by Wireloom from '03-alias-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusCollectionAliases;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="NestedSequence"/>.
/// </summary>
public class NestedSequenceSupport : TypeSupport<NestedSequence>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="NestedSequenceSupport"/> class.
    /// </summary>
    public NestedSequenceSupport() : base(
        new Implementation.NestedSequencePlugin(),
        new Lazy<DynamicType>(() => Implementation.NestedSequencePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static NestedSequenceSupport Instance { get; } = ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<NestedSequenceSupport, NestedSequence>();
}
