// <auto-generated/>
// This file was generated by Wireloom from '03-alias-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusCollectionAliases.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Sample"/>.
/// </summary>
public struct SampleUnmanaged : INativeTopicType<Sample>
{
    private NestedSequenceUnmanaged values;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        values.Destroy(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Sample sample, bool keysOnly = false)
    {
        values.FromNative(sample.values, keysOnly: false);
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        values.Initialize(allocatePointers, allocateMemory);
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Sample sample, bool keysOnly = false)
    {
        values.ToNative(sample.values, keysOnly: false);
    }
}
