// <auto-generated/>
// This file was generated by Wireloom from '03-alias-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusCollectionAliases;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="LongSequence"/>.
/// </summary>
public class LongSequenceSupport : TypeSupport<LongSequence>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="LongSequenceSupport"/> class.
    /// </summary>
    public LongSequenceSupport() : base(
        new Implementation.LongSequencePlugin(),
        new Lazy<DynamicType>(() => Implementation.LongSequencePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static LongSequenceSupport Instance { get; } = ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<LongSequenceSupport, LongSequence>();
}
