// <auto-generated/>
// This file was generated by Wireloom from '09-defaults-ranges.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusDefaultsAndRanges;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>09-defaults-ranges.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Sample : global::System.IEquatable<Sample>
{
    private int _value;
    private int _ranged;

    /// <summary>
    /// Gets or sets the <c>value</c> member. Its value must be between <c>0</c> and <c>100</c>. Its default value is <c>50</c>.
    /// </summary>
    public int value
    {
        get
        {
            return _value;
        }
        set
        {
            global::System.ArgumentOutOfRangeException.ThrowIfLessThan(value, 0);
            global::System.ArgumentOutOfRangeException.ThrowIfGreaterThan(value, 100);

            _value = value;
        }
    }

    /// <summary>
    /// Gets or sets the <c>ranged</c> member. Its value must be between <c>-32</c> and <c>31</c>.
    /// </summary>
    public int ranged
    {
        get
        {
            return _ranged;
        }
        set
        {
            global::System.ArgumentOutOfRangeException.ThrowIfLessThan(value, -32);
            global::System.ArgumentOutOfRangeException.ThrowIfGreaterThan(value, 31);

            _ranged = value;
        }
    }

    /// <summary>
    /// Gets or sets the <c>color</c> member. Its default value is <c>BLUE</c>.
    /// </summary>
    public Color color { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
        value = 50;
        color = (Color)2;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="value">The value for the <c>value</c> member.</param>
    /// <param name="ranged">The value for the <c>ranged</c> member.</param>
    /// <param name="color">The value for the <c>color</c> member.</param>
    public Sample(int value, int ranged, Color color)
    {
        this._value = value;
        this._ranged = ranged;
        this.color = color;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        _value = other._value;
        _ranged = other._ranged;
        color = other.color;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(value);
        hash.Add(ranged);
        hash.Add(color);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return value.Equals(other.value)
            && ranged.Equals(other.ranged)
            && color.Equals(other.color);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
