// <auto-generated/>
// This file was generated by Wireloom from '09-defaults-ranges.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusDefaultsAndRanges;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>09-defaults-ranges.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Sample : global::System.IEquatable<Sample>
{
    private int _value;
    private int _ranged;

    /// <summary>
    /// Gets or sets the <c>value</c> member. Valid values are in the inclusive range <c>0</c> through <c>100</c>. Its default value is <c>50</c>.
    /// </summary>
    /// <exception cref="global::System.ArgumentOutOfRangeException">The assigned value is outside the inclusive range 0 through 100.</exception>
    public int value
    {
        get
        {
            return _value;
        }
        set
        {
            global::System.ArgumentOutOfRangeException.ThrowIfLessThan(value, 0);
            global::System.ArgumentOutOfRangeException.ThrowIfGreaterThan(value, 100);

            _value = value;
        }
    }

    /// <summary>
    /// Gets or sets the <c>ranged</c> member. Valid values are in the inclusive range <c>-32</c> through <c>31</c>.
    /// </summary>
    /// <exception cref="global::System.ArgumentOutOfRangeException">The assigned value is outside the inclusive range -32 through 31.</exception>
    public int ranged
    {
        get
        {
            return _ranged;
        }
        set
        {
            global::System.ArgumentOutOfRangeException.ThrowIfLessThan(value, -32);
            global::System.ArgumentOutOfRangeException.ThrowIfGreaterThan(value, 31);

            _ranged = value;
        }
    }

    /// <summary>
    /// Gets or sets the <c>color</c> member. Its default value is <c>BLUE</c>.
    /// </summary>
    public Color color { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    /// <remarks>explicit IDL defaults are applied.</remarks>
    public Sample()
    {
        value = 50;
        color = (Color)(2);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="value">The value for the <c>value</c> member.</param>
    /// <param name="ranged">The value for the <c>ranged</c> member.</param>
    /// <param name="color">The value for the <c>color</c> member.</param>
    /// <exception cref="global::System.ArgumentOutOfRangeException">A supplied member value is outside its declared range.</exception>
    public Sample(int value, int ranged, Color color)
    {
        this.value = value;
        this.ranged = ranged;
        this.color = color;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Sample();
    /// var copy = new Sample(original);
    /// </code>
    /// </example>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        _value = other._value;
        _ranged = other._ranged;
        color = other.color;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(value);
        hash.Add(ranged);
        hash.Add(color);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return value.Equals(other.value)
            && ranged.Equals(other.ranged)
            && color.Equals(other.color);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
