// <auto-generated/>
// This file was generated by Wireloom from '04-strings.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusStrings;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>04-strings.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Sample : global::System.IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>unbounded</c> member. Its maximum length is <c>255</c> UTF-8 bytes.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>This unbounded narrow IDL string has an effective limit of 255 UTF-8 bytes. The generated C# property does not enforce the effective limit when assigned.</remarks>
    [Bound(255)]
    public string unbounded { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the <c>bounded</c> member. Its maximum length is <c>8</c> UTF-8 bytes.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this narrow IDL string is measured in UTF-8 bytes. The generated C# property does not check the bound when assigned.</remarks>
    [Bound(8)]
    public string bounded { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the <c>wideUnbounded</c> member. Its maximum length is <c>255</c> UTF-16 code units.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>This unbounded wide IDL string has an effective limit of 255 UTF-16 code units. The generated C# property does not enforce the effective limit when assigned.</remarks>
    [Bound(255)]
    public string wideUnbounded { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the <c>wideBounded</c> member. Its maximum length is <c>8</c> UTF-16 code units.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this wide IDL string is measured in UTF-16 code units. The generated C# property does not check the bound when assigned.</remarks>
    [Bound(8)]
    public string wideBounded { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="unbounded">The value for the <c>unbounded</c> member.</param>
    /// <param name="bounded">The value for the <c>bounded</c> member.</param>
    /// <param name="wideUnbounded">The value for the <c>wideUnbounded</c> member.</param>
    /// <param name="wideBounded">The value for the <c>wideBounded</c> member.</param>
    public Sample(string unbounded, string bounded, string wideUnbounded, string wideBounded)
    {
        this.unbounded = unbounded;
        this.bounded = bounded;
        this.wideUnbounded = wideUnbounded;
        this.wideBounded = wideBounded;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Sample();
    /// var copy = new Sample(original);
    /// </code>
    /// </example>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        unbounded = other.unbounded;
        bounded = other.bounded;
        wideUnbounded = other.wideUnbounded;
        wideBounded = other.wideBounded;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(unbounded);
        hash.Add(bounded);
        hash.Add(wideUnbounded);
        hash.Add(wideBounded);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return unbounded.Equals(other.unbounded)
            && bounded.Equals(other.bounded)
            && wideUnbounded.Equals(other.wideUnbounded)
            && wideBounded.Equals(other.wideBounded);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
