// <auto-generated/>
// This file was generated by Wireloom from '04-strings.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusStrings;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Sample"/>.
/// </summary>
public class SampleSupport : TypeSupport<Sample>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="SampleSupport"/> class.
    /// </summary>
    public SampleSupport() : base(
        new Implementation.SamplePlugin(),
        new Lazy<DynamicType>(() => Implementation.SamplePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static SampleSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<SampleSupport, Sample>();
}
