// <auto-generated/>
// This file was generated by Wireloom from '06-alias-composition.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusAggregateComposition;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Identifier"/>.
/// </summary>
public class IdentifierSupport : TypeSupport<Identifier>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="IdentifierSupport"/> class.
    /// </summary>
    public IdentifierSupport() : base(
        new Implementation.IdentifierPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.IdentifierPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for formatting, serialization, and dynamic-type utilities for this typedef.
    /// </summary>
    /// <remarks>The generated plugin and unmanaged type are runtime implementation details; application code should use this support class and the managed typedef.</remarks>
    public static IdentifierSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<IdentifierSupport, Identifier>();
}
