// <auto-generated/>
// This file was generated by Wireloom from '06-alias-composition.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusAggregateComposition;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>06-alias-composition.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Sample : IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>id</c> member.
    /// </summary>
    public int id { get; set; }

    /// <summary>
    /// Gets or sets the <c>state</c> member.
    /// </summary>
    public State state { get; set; } = (State)0;

    /// <summary>
    /// Gets the <c>values</c> member. Its maximum number of elements is <c>4</c>.
    /// </summary>
    [Bound(4)]
    public ISequence<float> values { get; } = null!;

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
        values = new Sequence<float>();
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="id">The value for the <c>id</c> member.</param>
    /// <param name="state">The value for the <c>state</c> member.</param>
    /// <param name="values">The value for the <c>values</c> member.</param>
    public Sample(int id, State state, ISequence<float> values)
    {
        this.id = id;
        this.state = state;
        this.values = values;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        id = other.id;
        state = other.state;
        values = new Sequence<float>(other.values);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(id);
        hash.Add(state);
        hash.Add(values.Count);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return id.Equals(other.id)
            && state.Equals(other.state)
            && values.SequenceEqual(other.values);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
