// <auto-generated/>
// This file was generated by Wireloom from '06-alias-composition.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusAggregateComposition;

/// <summary>
/// Provides the <c>Max</c> IDL constant.
/// </summary>
public static class Max
{
    /// <summary>
    /// Gets the integer value of the <c>Max</c> IDL constant.
    /// </summary>
    public const int Value = 4;
}
