// <auto-generated/>
// This file was generated by Wireloom from '03-alias-aggregate.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusAggregateAliases;

/// <summary>
/// Represents the <c>PointAlias2</c> IDL typedef declared in <c>03-alias-aggregate.idl</c>.
/// </summary>
public partial class PointAlias2 : IEquatable<PointAlias2>
{
    /// <summary>
    /// Gets or sets the value represented by this typedef.
    /// </summary>
    public Point Value { get; set; } = null!;

    /// <summary>
    /// Initializes an empty typedef value.
    /// </summary>
    public PointAlias2()
    {
    }

    /// <summary>
    /// Initializes the typedef with a value.
    /// </summary>
    /// <param name="Value">The value to store.</param>
    public PointAlias2(Point Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another typedef value.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    public PointAlias2(PointAlias2? other)
    {
        if (other is not null)
        {
            Value = other.Value;
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(Value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    public bool Equals(PointAlias2? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as PointAlias2);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this typedef.
    /// </summary>
    public override string ToString() => PointAlias2Support.Instance.ToString(this);
}
