// <auto-generated/>
// This file was generated by Wireloom from '03-alias-aggregate.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusAggregateAliases.Implementation;

internal class PointAlias2Plugin : InterpretedTypePlugin<PointAlias2, PointAlias2Unmanaged>
{
    internal PointAlias2Plugin() : base("CorpusAggregateAliases.PointAlias2", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="PointAlias2"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        return tsf.CreateAliasWithAccessInfo<PointAlias2Unmanaged>(dtf, "PointAlias2", dtf.GetPrimitiveType<Point>());
    }
}
