// <auto-generated/>
// This file was generated by Wireloom from '03-alias-aggregate.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusAggregateAliases;

/// <summary>
/// Represents the <c>PointAlias</c> IDL typedef declared in <c>03-alias-aggregate.idl</c>.
/// </summary>
public partial class PointAlias : global::System.IEquatable<PointAlias>
{
    /// <summary>
    /// Gets or sets the value represented by this typedef.
    /// </summary>
    public Point Value { get; set; } = null!;

    /// <summary>
    /// Initializes the typedef value to its default value.
    /// </summary>
    public PointAlias()
    {
    }

    /// <summary>
    /// Initializes the typedef with a value.
    /// </summary>
    /// <param name="Value">The value to store.</param>
    /// <remarks>The constructor stores the supplied reference as provided; it does not make a copy.</remarks>
    public PointAlias(Point Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another typedef value.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor returns without copying and keeps its property initializer. An aggregate value is copied through its generated copy constructor.</remarks>
    public PointAlias(PointAlias? other)
    {
        if (other is not null)
        {
            Value = other.Value is null ? null! : new Point(other.Value);
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(Value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    /// <returns><see langword="true"/> when both typedefs have equal values; otherwise, <see langword="false"/>.</returns>
    public bool Equals(PointAlias? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as PointAlias);

    /// <summary>
    /// Formats this typedef as readable text.
    /// </summary>
    /// <returns>A readable string formatted by this typedef's type-support instance.</returns>
    public override string ToString() => PointAliasSupport.Instance.ToString(this);
}
