// <auto-generated/>
// This file was generated by Wireloom from '13-modules.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusIntegration.Contracts;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="NamespacedMessage"/>.
/// </summary>
public class NamespacedMessageSupport : TypeSupport<NamespacedMessage>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="NamespacedMessageSupport"/> class.
    /// </summary>
    public NamespacedMessageSupport() : base(
        new Implementation.NamespacedMessagePlugin(),
        new Lazy<DynamicType>(() => Implementation.NamespacedMessagePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static NamespacedMessageSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<NamespacedMessageSupport, NamespacedMessage>();
}
