// <auto-generated/>
// This file was generated by Wireloom from '02-formatting.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusFormatting;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Value"/>.
/// </summary>
public class ValueSupport : TypeSupport<Value>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ValueSupport"/> class.
    /// </summary>
    public ValueSupport() : base(
        new Implementation.ValuePlugin(),
        new Lazy<DynamicType>(() => Implementation.ValuePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static ValueSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ValueSupport, Value>();
}
