// <auto-generated/>
// This file was generated by Wireloom from '05-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusCollections;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="BoundedLongs"/>.
/// </summary>
public class BoundedLongsSupport : TypeSupport<BoundedLongs>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="BoundedLongsSupport"/> class.
    /// </summary>
    public BoundedLongsSupport() : base(
        new Implementation.BoundedLongsPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.BoundedLongsPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for formatting, serialization, and dynamic-type utilities for this typedef.
    /// </summary>
    /// <remarks>The generated plugin and unmanaged type are runtime implementation details; application code should use this support class and the managed typedef.</remarks>
    public static BoundedLongsSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<BoundedLongsSupport, BoundedLongs>();
}
