// <auto-generated/>
// This file was generated by Wireloom from '05-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusCollections;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="CoordinateGrid"/>.
/// </summary>
public class CoordinateGridSupport : TypeSupport<CoordinateGrid>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CoordinateGridSupport"/> class.
    /// </summary>
    public CoordinateGridSupport() : base(
        new Implementation.CoordinateGridPlugin(),
        new Lazy<DynamicType>(() => Implementation.CoordinateGridPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static CoordinateGridSupport Instance { get; } = ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<CoordinateGridSupport, CoordinateGrid>();
}
