// <auto-generated/>
// This file was generated by Wireloom from '05-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusCollections;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>05-collections.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Sample : IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>values</c> member.
    /// </summary>
    public int[,] values { get; set; } = null!;

    /// <summary>
    /// Gets the <c>unbounded</c> member. Its maximum number of elements is <c>100</c>.
    /// </summary>
    [Bound(100)]
    public ISequence<int> unbounded { get; } = null!;

    /// <summary>
    /// Gets or sets the <c>bounded</c> member. Its maximum number of elements is <c>4</c>.
    /// </summary>
    [Bound(4)]
    public BoundedLongs bounded { get; set; } = new BoundedLongs();

    /// <summary>
    /// Gets the <c>items</c> member. Its maximum number of elements is <c>2</c>.
    /// </summary>
    [Bound(2)]
    public ISequence<Item> items { get; } = null!;

    /// <summary>
    /// Gets or sets the <c>grid</c> member.
    /// </summary>
    public CoordinateGrid grid { get; set; } = new CoordinateGrid();

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
        unbounded = new Sequence<int>();
        items = new Sequence<Item>();
        values = new int[2, 3];
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="values">The value for the <c>values</c> member.</param>
    /// <param name="unbounded">The value for the <c>unbounded</c> member.</param>
    /// <param name="bounded">The value for the <c>bounded</c> member.</param>
    /// <param name="items">The value for the <c>items</c> member.</param>
    /// <param name="grid">The value for the <c>grid</c> member.</param>
    public Sample(int[,] values, ISequence<int> unbounded, BoundedLongs bounded, ISequence<Item> items, CoordinateGrid grid)
    {
        this.values = values;
        this.unbounded = unbounded;
        this.bounded = bounded;
        this.items = items;
        this.grid = grid;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        values = (int[,])other.values.Clone();
        unbounded = new Sequence<int>(other.unbounded);
        bounded = new BoundedLongs(other.bounded);
        items = new Sequence<Item>(other.items.Select(element => new Item(element)));
        grid = new CoordinateGrid(other.grid);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(values[0]);
        hash.Add(unbounded.Count);
        hash.Add(bounded);
        hash.Add(items.Count);
        hash.Add(grid);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return values.SequenceEqual(other.values)
            && unbounded.SequenceEqual(other.unbounded)
            && bounded.Equals(other.bounded)
            && items.SequenceEqual(other.items)
            && grid.Equals(other.grid);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
