// <auto-generated/>
// This file was generated by Wireloom from '05-collections.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusCollections;

/// <summary>
/// Represents the <c>CoordinateGrid</c> IDL typedef declared in <c>05-collections.idl</c>.
/// </summary>
public partial class CoordinateGrid : IEquatable<CoordinateGrid>
{
    /// <summary>
    /// Gets or sets the array value represented by this typedef.
    /// </summary>
    public int[,] Value { get; set; } = new int[2, 3];

    /// <summary>
    /// Initializes an empty array typedef.
    /// </summary>
    public CoordinateGrid()
    {
    }

    /// <summary>
    /// Initializes the typedef with an array value.
    /// </summary>
    /// <param name="Value">The array value to store.</param>
    public CoordinateGrid(int[,] Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another array typedef.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    public CoordinateGrid(CoordinateGrid? other)
    {
        if (other is null)
        {
            return;
        }

        Value = (int[,])other.Value.Clone();
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Value.Cast<int>().First().GetHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same array values as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    public bool Equals(CoordinateGrid? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Rank == other.Value.Rank
            && Value.Cast<int>().SequenceEqual(other.Value.Cast<int>());
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as CoordinateGrid);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this typedef.
    /// </summary>
    public override string ToString() => CoordinateGridSupport.Instance.ToString(this);
}
