// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusAggregates;

/// <summary>
/// Represents the <c>Base</c> DDS type declared in <c>06-aggregates.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Base : IEquatable<Base>
{
    /// <summary>
    /// Gets or sets the <c>base</c> member.
    /// </summary>
    public int @base { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Base"/> class.
    /// </summary>
    public Base()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Base"/> class with the supplied member values.
    /// </summary>
    /// <param name="@base">The value for the <c>base</c> member.</param>
    public Base(int @base)
    {
        this.@base = @base;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Base"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Base(Base? other)
    {
        if (other is null)
        {
            return;
        }

        @base = other.@base;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(@base);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Base? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return @base.Equals(other.@base);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Base);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => BaseSupport.Instance.ToString(this);
}
