// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusAggregates;

/// <summary>
/// Represents the <c>Derived</c> DDS type declared in <c>06-aggregates.idl</c>. It derives from <see cref="Base"/>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Derived : Base, global::System.IEquatable<Derived>
{
    /// <summary>
    /// Gets or sets the <c>derived</c> member. Its maximum length is <c>16</c> UTF-8 bytes.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this narrow IDL string is measured in UTF-8 bytes. The generated C# property does not check the bound when assigned.</remarks>
    [Bound(16)]
    public string derived { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Derived"/> class.
    /// </summary>
    public Derived()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Derived"/> class with the supplied member values.
    /// </summary>
    /// <param name="base">The value for the <c>base</c> member.</param>
    /// <param name="derived">The value for the <c>derived</c> member.</param>
    public Derived(int @base, string derived) : base(@base)
    {
        this.derived = derived;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Derived"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Derived();
    /// var copy = new Derived(original);
    /// </code>
    /// </example>
    public Derived(Derived? other) : base(other)
    {
        if (other is null)
        {
            return;
        }

        derived = other.derived;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(base.GetHashCode());
        hash.Add(derived);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Derived? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        if (!base.Equals(other))
        {
            return false;
        }

        return derived.Equals(other.derived);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Derived);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => DerivedSupport.Instance.ToString(this);
}
