// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusAggregates;

/// <summary>
/// Represents the <c>Derived</c> DDS type declared in <c>06-aggregates.idl</c>. It derives from <see cref="Base"/>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Derived : Base, IEquatable<Derived>
{
    /// <summary>
    /// Gets or sets the <c>derived</c> member. Its maximum length is <c>16</c>.
    /// </summary>
    [Bound(16)]
    public string derived { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Derived"/> class.
    /// </summary>
    public Derived()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Derived"/> class with the supplied member values.
    /// </summary>
    /// <param name="@base">The value for the <c>base</c> member.</param>
    /// <param name="derived">The value for the <c>derived</c> member.</param>
    public Derived(int @base, string derived) : base(@base)
    {
        this.derived = derived;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Derived"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Derived(Derived? other) : base(other)
    {
        if (other is null)
        {
            return;
        }

        derived = other.derived;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(base.GetHashCode());
        hash.Add(derived);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Derived? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        if (!base.Equals(other))
        {
            return false;
        }

        return derived.Equals(other.derived);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Derived);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => DerivedSupport.Instance.ToString(this);
}
