// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusAggregates;

/// <summary>
/// Represents the <c>Recursive</c> DDS type declared in <c>06-aggregates.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Recursive : IEquatable<Recursive>
{
    /// <summary>
    /// Gets or sets the <c>value</c> member.
    /// </summary>
    public int value { get; set; }

    /// <summary>
    /// Gets the <c>children</c> member. Its maximum number of elements is <c>100</c>.
    /// </summary>
    [Bound(100)]
    public ISequence<Recursive> children { get; } = null!;

    /// <summary>
    /// Initializes a new instance of the <see cref="Recursive"/> class.
    /// </summary>
    public Recursive()
    {
        children = new Sequence<Recursive>();
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Recursive"/> class with the supplied member values.
    /// </summary>
    /// <param name="value">The value for the <c>value</c> member.</param>
    /// <param name="children">The value for the <c>children</c> member.</param>
    public Recursive(int value, ISequence<Recursive> children)
    {
        this.value = value;
        this.children = children;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Recursive"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Recursive(Recursive? other)
    {
        if (other is null)
        {
            return;
        }

        value = other.value;
        children = new Sequence<Recursive>(other.children.Select(element => new Recursive(element)));
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(value);
        hash.Add(children.Count);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Recursive? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return value.Equals(other.value)
            && children.SequenceEqual(other.children);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Recursive);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => RecursiveSupport.Instance.ToString(this);
}
