// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusAggregates.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Recursive"/>.
/// </summary>
public struct RecursiveUnmanaged : INativeTopicType<Recursive>
{
    private int value;
    private NativeSeq children;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        children.Destroy<Recursive, RecursiveUnmanaged>(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Recursive sample, bool keysOnly = false)
    {
        sample.value = value;
        children.FromNative<Recursive, RecursiveUnmanaged>(sample.children);
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        value = 0;
        children.Initialize<Recursive, RecursiveUnmanaged>(max: 100, absoluteMax: 100, allocateMemory: allocateMemory);
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Recursive sample, bool keysOnly = false)
    {
        value = sample.value;
        children.ToNative<Recursive, RecursiveUnmanaged>(sample.children);
    }
}
