// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusAggregates;

/// <summary>
/// Represents the <c>Composed</c> DDS type declared in <c>06-aggregates.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Composed : IEquatable<Composed>
{
    /// <summary>
    /// Gets or sets the <c>base</c> member.
    /// </summary>
    public Base @base { get; set; } = new Base();

    /// <summary>
    /// Gets or sets the <c>derived</c> member.
    /// </summary>
    public Derived derived { get; set; } = new Derived();

    /// <summary>
    /// Initializes a new instance of the <see cref="Composed"/> class.
    /// </summary>
    public Composed()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Composed"/> class with the supplied member values.
    /// </summary>
    /// <param name="@base">The value for the <c>base</c> member.</param>
    /// <param name="derived">The value for the <c>derived</c> member.</param>
    public Composed(Base @base, Derived derived)
    {
        this.@base = @base;
        this.derived = derived;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Composed"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Composed(Composed? other)
    {
        if (other is null)
        {
            return;
        }

        @base = new Base(other.@base);
        derived = new Derived(other.derived);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(@base);
        hash.Add(derived);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Composed? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return @base.Equals(other.@base)
            && derived.Equals(other.derived);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Composed);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => ComposedSupport.Instance.ToString(this);
}
