// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusAggregates.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Derived"/>.
/// </summary>
internal class DerivedPlugin : InterpretedTypePlugin<Derived, DerivedUnmanaged>
{
    internal DerivedPlugin() : base("CorpusAggregates.Derived", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Derived"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("derived", dtf.CreateString(16), id: 1)
        };

        var result = tsf.CreateTypeWithAccessInfo<DerivedUnmanaged>(
            dtf.BuildStruct()
                .WithParent((StructType) BaseSupport.Instance.GetDynamicTypeInternal(isPublic))
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusAggregates::Derived")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.String,
                defaultValue: new AnnotationParameterValue { StringValue = "" },
                minValue: null,
                maxValue: null,
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        return result;
    }
}
