// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusAggregates;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Composed"/>.
/// </summary>
public class ComposedSupport : TypeSupport<Composed>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ComposedSupport"/> class.
    /// </summary>
    public ComposedSupport() : base(
        new Implementation.ComposedPlugin(),
        new Lazy<DynamicType>(() => Implementation.ComposedPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static ComposedSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ComposedSupport, Composed>();
}
