// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusAggregates.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Recursive"/>.
/// </summary>
internal class RecursivePlugin : InterpretedTypePlugin<Recursive, RecursiveUnmanaged>
{
    private static DynamicType? dynamicType;
    private static bool isInitialized;

    internal RecursivePlugin() : base("CorpusAggregates.Recursive", isKeyed: false, CreateDynamicType(isPublic: false))
    {
        isRecursiveType = true;
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Recursive"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        if (isPublic)
        {
            throw new global::System.NotSupportedException("Recursive types don't support the property TypeSupport.DynamicType");
        }

        if (isInitialized)
        {
            dynamicType = tsf.CreateTypeWithAccessInfo<RecursiveUnmanaged>(dtf.BuildStruct()
    .WithExtensibility(ExtensibilityKind.Extensible)
    .WithName("CorpusAggregates::Recursive"));
            return dynamicType;
        }
        isInitialized = true;


        var members = new StructMember[]
        {
            new StructMember("value", dtf.GetPrimitiveType<int>(), id: 0),
            new StructMember("children", tsf.CreateSequenceWithAccessInfo(dtf, RecursiveSupport.GetOrCreateInstanceImpl().GetDynamicTypeInternal(isPublic), 100), id: 1)
        };

        var result = tsf.CreateTypeWithAccessInfo<RecursiveUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusAggregates::Recursive")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        if (dynamicType != null && ((StructType)dynamicType).MemberCount == 0)
        {
            tsf.SetStructMembers((StructType)dynamicType, members);
        }
        isInitialized = false;

        return result;
    }
}
