// <auto-generated/>
// This file was generated by Wireloom from '06-aggregates.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusAggregates.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Composed"/>.
/// </summary>
public struct ComposedUnmanaged : INativeTopicType<Composed>
{
    private BaseUnmanaged @base;
    private DerivedUnmanaged derived;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        @base.Destroy(optionalsOnly);
        derived.Destroy(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Composed sample, bool keysOnly = false)
    {
        @base.FromNative(sample.@base, keysOnly: false);
        derived.FromNative(sample.derived, keysOnly: false);
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        @base.Initialize(allocatePointers, allocateMemory);
        derived.Initialize(allocatePointers, allocateMemory);
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Composed sample, bool keysOnly = false)
    {
        @base.ToNative(sample.@base, keysOnly: false);
        derived.ToNative(sample.derived, keysOnly: false);
    }
}
