// <auto-generated/>
// This file was generated by Wireloom from '01-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusPrimitiveBoundaries;

/// <summary>
/// Provides the <c>longLongMax</c> IDL constant.
/// </summary>
public static class longLongMax
{
    /// <summary>
    /// Gets the long long value of the <c>longLongMax</c> IDL constant.
    /// </summary>
    public const long Value = 9223372036854775807L;
}
