// <auto-generated/>
// This file was generated by Wireloom from '01-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusPrimitiveBoundaries.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Sample"/>.
/// </summary>
public struct SampleUnmanaged : INativeTopicType<Sample>
{
    private short shortValue;
    private int longValue;
    private long longLongValue;
    private sbyte int8Value;
    private long int64Value;
    private float floatValue;
    private double doubleValue;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Sample sample, bool keysOnly = false)
    {
        sample.shortValue = shortValue;
        sample.longValue = longValue;
        sample.longLongValue = longLongValue;
        sample.int8Value = int8Value;
        sample.int64Value = int64Value;
        sample.floatValue = floatValue;
        sample.doubleValue = doubleValue;
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        shortValue = 0;
        longValue = 0;
        longLongValue = 0L;
        int8Value = 0;
        int64Value = 0L;
        floatValue = 0.0F;
        doubleValue = 0.0D;
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Sample sample, bool keysOnly = false)
    {
        shortValue = sample.shortValue;
        longValue = sample.longValue;
        longLongValue = sample.longLongValue;
        int8Value = sample.int8Value;
        int64Value = sample.int64Value;
        floatValue = sample.floatValue;
        doubleValue = sample.doubleValue;
    }
}
