// <auto-generated/>
// This file was generated by Wireloom from '01-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusPrimitiveBoundaries;

/// <summary>
/// Provides the <c>longMax</c> IDL constant.
/// </summary>
public static class longMax
{
    /// <summary>
    /// Gets the integer value of the <c>longMax</c> IDL constant.
    /// </summary>
    public const int Value = 2147483647;
}
