// <auto-generated/>
// This file was generated by Wireloom from '01-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusPrimitiveBoundaries;

/// <summary>
/// Provides the <c>int64Min</c> IDL constant.
/// </summary>
public static class int64Min
{
    /// <summary>
    /// Gets the int64 value of the <c>int64Min</c> IDL constant.
    /// </summary>
    public const long Value = long.MinValue;
}
