// <auto-generated/>
// This file was generated by Wireloom from '01-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusPrimitiveBoundaries;

/// <summary>
/// Provides the <c>shortMax</c> IDL constant.
/// </summary>
public static class shortMax
{
    /// <summary>
    /// Gets the short value of the <c>shortMax</c> IDL constant.
    /// </summary>
    public const short Value = 32767;
}
