// <auto-generated/>
// This file was generated by Wireloom from '09-id-gaps.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusIdGaps;

/// <summary>
/// Represents the <c>Message</c> DDS type declared in <c>09-id-gaps.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Message : global::System.IEquatable<Message>
{
    /// <summary>
    /// Gets or sets the <c>first</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>. Its DDS member ID is <c>1</c>, which identifies this member for type compatibility; it is separate from the DDS instance key.
    /// </summary>
    public int first { get; set; }

    /// <summary>
    /// Gets or sets the <c>seventh</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>. Its DDS member ID is <c>7</c>, which identifies this member for type compatibility; it is separate from the DDS instance key.
    /// </summary>
    public int seventh { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Message"/> class.
    /// </summary>
    public Message()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Message"/> class with the supplied member values.
    /// </summary>
    /// <param name="first">The value for the <c>first</c> member.</param>
    /// <param name="seventh">The value for the <c>seventh</c> member.</param>
    public Message(int first, int seventh)
    {
        this.first = first;
        this.seventh = seventh;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Message"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Message();
    /// var copy = new Message(original);
    /// </code>
    /// </example>
    public Message(Message? other)
    {
        if (other is null)
        {
            return;
        }

        first = other.first;
        seventh = other.seventh;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(first);
        hash.Add(seventh);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Message? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return first.Equals(other.first)
            && seventh.Equals(other.seventh);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Message);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => MessageSupport.Instance.ToString(this);
}
