// <auto-generated/>
// This file was generated by Wireloom from '13-status.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="CorpusIntegrationStatus"/>.
/// </summary>
internal class CorpusIntegrationStatusPlugin : InterpretedTypePlugin<CorpusIntegrationStatus, CorpusIntegrationStatusUnmanaged>
{
    internal CorpusIntegrationStatusPlugin() : base("CorpusIntegrationStatus", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="CorpusIntegrationStatus"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("active", dtf.GetPrimitiveType<bool>(), id: 0)
        };

        var result = tsf.CreateTypeWithAccessInfo<CorpusIntegrationStatusUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusIntegrationStatus")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Boolean,
                defaultValue: new AnnotationParameterValue { BoolValue = false },
                minValue: null,
                maxValue: null,
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        return result;
    }
}
