// <auto-generated/>
// This file was generated by Wireloom from '07-unions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusUnions;

/// <summary>
/// Represents the <c>Choice</c> DDS union declared in <c>07-unions.idl</c>. Exactly one branch is selected by <see cref="Discriminator"/>.
/// </summary>
public partial class Choice : IEquatable<Choice>
{
    private int _number;
    private string _text = string.Empty;
    private bool _flag;

    /// <summary>
    /// Gets the discriminator that selects the active DDS union branch.
    /// </summary>
    public int Discriminator { get; private set; }

    /// <summary>
    /// Gets the discriminator value used to initialize this union.
    /// </summary>
    public const int DefaultDiscriminator = 0;

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>0</c>.
    /// </summary>
    public int number
    {
        get
        {
            if (Discriminator != 0)
            {
                throw new InvalidOperationException("number not selected");
            }

            return _number;
        }
        set
        {
            _number = value;

            Discriminator = 0;
        }
    }

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>1</c>.
    /// </summary>
    [Bound(255)]
    public string text
    {
        get
        {
            if (Discriminator != 1)
            {
                throw new InvalidOperationException("text not selected");
            }

            return _text;
        }
        set
        {
            _text = value;

            Discriminator = 1;
        }
    }

    /// <summary>
    /// Gets or sets the default union branch, selected when the discriminator does not match an explicit case.
    /// </summary>
    public bool flag
    {
        get
        {
            if (Discriminator == 0 || Discriminator == 1)
            {
                throw new InvalidOperationException("flag not selected");
            }

            return _flag;
        }
        set
        {
            _flag = value;

            Discriminator = 2;
        }
    }

    /// <summary>
    /// Initializes a new union with its RTI default discriminator.
    /// </summary>
    public Choice()
    {
        Discriminator = DefaultDiscriminator;
    }

    /// <summary>
    /// Initializes a copy of another <see cref="Choice"/> union.
    /// </summary>
    /// <param name="other">The union to copy.</param>
    public Choice(Choice? other)
    {
        if (other is null)
        {
            return;
        }

        Discriminator = other.Discriminator;

        switch (Discriminator)
        {
            case 0:
                this._number = other.number;
                break;
            case 1:
                this._text = other.text;
                break;
            default:
                this._flag = other.flag;
                break;
        }
    }

    /// <summary>
    /// Sets the default branch with an explicit discriminator value.
    /// </summary>
    /// <param name="value">The value for the default branch.</param>
    /// <param name="discriminator">A discriminator value that does not select an explicit branch.</param>
    public void Setflag(bool value, int discriminator)
    {
        if (discriminator == 0 || discriminator == 1)
        {
            throw new ArgumentException("Invalid discriminator value for flag", nameof(discriminator));
        }

        _flag = value;

        Discriminator = discriminator;
    }

    /// <summary>
    /// Gets the currently active union-branch value.
    /// </summary>
    /// <returns>The value of the branch selected by <see cref="Discriminator"/>.</returns>
    public object Get()
    {
        return Discriminator switch
        {
            0 => number,
            1 => text,
            _ => flag,
        };
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Discriminator switch
        {
            0 => HashCode.Combine(Discriminator, number),
            1 => HashCode.Combine(Discriminator, text),
            _ => HashCode.Combine(Discriminator, flag),
        };
    }

    /// <summary>
    /// Determines whether this union has the same discriminator and active branch value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The union to compare.</param>
    /// <returns><see langword="true"/> when both unions select equal values; otherwise <see langword="false"/>.</returns>
    public bool Equals(Choice? other)
    {
        if (other is null || Discriminator != other.Discriminator)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return Discriminator switch
        {
            0 => number.Equals(other.number),
            1 => text.Equals(other.text),
            _ => flag.Equals(other.flag),
        };
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Choice);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this union.
    /// </summary>
    public override string ToString() => ChoiceSupport.Instance.ToString(this);
}
