// <auto-generated/>
// This file was generated by Wireloom from '08-keys.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;

namespace CorpusKeys;

/// <summary>
/// Represents the <c>Simple</c> DDS type declared in <c>08-keys.idl</c>. Its key members identify a DDS instance across samples; they do not determine whether two complete samples are equal. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Simple : global::System.IEquatable<Simple>
{
    /// <summary>
    /// Gets or sets the <c>id</c> member. This member forms part of the DDS instance key. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>.
    /// </summary>
    [Key]
    public int id { get; set; }

    /// <summary>
    /// Gets or sets the <c>name</c> member. Its maximum length is <c>16</c> UTF-8 bytes.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this narrow IDL string is measured in UTF-8 bytes. The generated C# property does not check the bound when assigned.</remarks>
    [Bound(16)]
    public string name { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Simple"/> class.
    /// </summary>
    public Simple()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Simple"/> class with the supplied member values.
    /// </summary>
    /// <param name="id">The value for the <c>id</c> member.</param>
    /// <param name="name">The value for the <c>name</c> member.</param>
    public Simple(int id, string name)
    {
        this.id = id;
        this.name = name;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Simple"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Simple();
    /// var copy = new Simple(original);
    /// </code>
    /// </example>
    public Simple(Simple? other)
    {
        if (other is null)
        {
            return;
        }

        id = other.id;
        name = other.name;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(id);
        hash.Add(name);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Simple? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return id.Equals(other.id)
            && name.Equals(other.name);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Simple);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SimpleSupport.Instance.ToString(this);
}
