// <auto-generated/>
// This file was generated by Wireloom from '02-names-constants.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusNames.Nested;

/// <summary>
/// Represents the <c>Point</c> DDS type declared in <c>02-names-constants.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Point : IEquatable<Point>
{
    /// <summary>
    /// Gets or sets the <c>x</c> member.
    /// </summary>
    public int x { get; set; }

    /// <summary>
    /// Gets or sets the <c>y</c> member.
    /// </summary>
    public int y { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Point"/> class.
    /// </summary>
    public Point()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Point"/> class with the supplied member values.
    /// </summary>
    /// <param name="x">The value for the <c>x</c> member.</param>
    /// <param name="y">The value for the <c>y</c> member.</param>
    public Point(int x, int y)
    {
        this.x = x;
        this.y = y;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Point"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Point(Point? other)
    {
        if (other is null)
        {
            return;
        }

        x = other.x;
        y = other.y;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(x);
        hash.Add(y);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Point? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return x.Equals(other.x)
            && y.Equals(other.y);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Point);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => PointSupport.Instance.ToString(this);
}
