// <auto-generated/>
// This file was generated by Wireloom from '02-names-constants.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusNames.Nested;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Point"/>.
/// </summary>
public class PointSupport : TypeSupport<Point>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PointSupport"/> class.
    /// </summary>
    public PointSupport() : base(
        new Implementation.PointPlugin(),
        new Lazy<DynamicType>(() => Implementation.PointPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static PointSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<PointSupport, Point>();
}
