// <auto-generated/>
// This file was generated by Wireloom from '02-names-constants.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusNames;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="State"/>.
/// </summary>
public class StateSupport : TypeSupport<State>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="StateSupport"/> class.
    /// </summary>
    public StateSupport() : base(
        new Implementation.StatePlugin(),
        new Lazy<DynamicType>(() => Implementation.StatePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static StateSupport Instance { get; } = ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<StateSupport, State>();
}
