// <auto-generated/>
// This file was generated by Wireloom from '09-extensibility.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusExtensibility;

/// <summary>
/// Represents the <c>Mutable</c> DDS type declared in <c>09-extensibility.idl</c>. It is marked as <c>mutable</c>.
/// </summary>
public partial class Mutable : IEquatable<Mutable>
{
    /// <summary>
    /// Gets or sets the <c>id</c> member.
    /// </summary>
    public int id { get; set; }

    /// <summary>
    /// Gets or sets the <c>optionalValue</c> member. This member is optional.
    /// </summary>
    [Optional]
    public int? optionalValue { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Mutable"/> class.
    /// </summary>
    public Mutable()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Mutable"/> class with the supplied member values.
    /// </summary>
    /// <param name="id">The value for the <c>id</c> member.</param>
    /// <param name="optionalValue">The value for the <c>optionalValue</c> member.</param>
    public Mutable(int id, int? optionalValue)
    {
        this.id = id;
        this.optionalValue = optionalValue;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Mutable"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Mutable(Mutable? other)
    {
        if (other is null)
        {
            return;
        }

        id = other.id;
        optionalValue = other.optionalValue;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(id);
        hash.Add(optionalValue);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Mutable? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return id.Equals(other.id)
            && Equals(optionalValue, other.optionalValue);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Mutable);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => MutableSupport.Instance.ToString(this);
}
