// <auto-generated/>
// This file was generated by Wireloom from '09-extensibility.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusExtensibility.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Mutable"/>.
/// </summary>
public struct MutableUnmanaged : INativeTopicType<Mutable>
{
    private int id;
    private NativeUnmanagedOptional optionalValue;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        optionalValue.Destroy(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Mutable sample, bool keysOnly = false)
    {
        sample.id = id;
        sample.optionalValue = optionalValue.FromNative<int>();
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        id = 0;
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Mutable sample, bool keysOnly = false)
    {
        id = sample.id;
        optionalValue.ToNative<int>(sample.optionalValue);
    }
}
