// <auto-generated/>
// This file was generated by Wireloom from '09-extensibility.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;

namespace CorpusExtensibility;

/// <summary>
/// Represents the <c>Mutable</c> DDS type declared in <c>09-extensibility.idl</c>. It is marked as <c>mutable</c>. Members may be identified and reordered by DDS member IDs during compatible type evolution.
/// </summary>
public partial class Mutable : global::System.IEquatable<Mutable>
{
    /// <summary>
    /// Gets or sets the <c>id</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>. Its DDS member ID is <c>1</c>, which identifies this member for type compatibility; it is separate from the DDS instance key.
    /// </summary>
    public int id { get; set; }

    /// <summary>
    /// Gets or sets the <c>optionalValue</c> member. This member is optional. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>. A <see langword="null"/> value means the member is absent. Its DDS member ID is <c>2</c>, which identifies this member for type compatibility; it is separate from the DDS instance key.
    /// </summary>
    /// <example>
    /// <code>
    /// var sample = new Mutable();
    /// sample.optionalValue = null; // the member is absent
    /// </code>
    /// </example>
    [Optional]
    public int? optionalValue { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Mutable"/> class.
    /// </summary>
    public Mutable()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Mutable"/> class with the supplied member values.
    /// </summary>
    /// <param name="id">The value for the <c>id</c> member.</param>
    /// <param name="optionalValue">The value for the <c>optionalValue</c> member.</param>
    public Mutable(int id, int? optionalValue)
    {
        this.id = id;
        this.optionalValue = optionalValue;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Mutable"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Mutable();
    /// var copy = new Mutable(original);
    /// </code>
    /// </example>
    public Mutable(Mutable? other)
    {
        if (other is null)
        {
            return;
        }

        id = other.id;
        optionalValue = other.optionalValue;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(id);
        hash.Add(optionalValue);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Mutable? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return id.Equals(other.id)
            && Equals(optionalValue, other.optionalValue);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Mutable);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => MutableSupport.Instance.ToString(this);
}
