#!/usr/bin/env python3
"""Discover generated topic types and emit a stable case registry."""

import json
import re
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) not in (4, 5):
        raise SystemExit("usage: discover_cases.py <manifest> <generated-root> <output> [case-id]")

    manifest_path = Path(sys.argv[1]).resolve()
    generated_root = Path(sys.argv[2]).resolve()
    output_path = Path(sys.argv[3]).resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    exclusions_path = Path(__file__).resolve().parents[1] / "wire-case-exclusions.json"
    excluded_ids = {
        case["id"]
        for case in json.loads(exclusions_path.read_text(encoding="utf-8"))["cases"]
    }
    requested_case = sys.argv[4] if len(sys.argv) == 5 else None
    selected_cases = [
        case for case in manifest["positiveCases"]
        if case["id"] not in excluded_ids
        if requested_case is None or case["id"] == requested_case
    ]
    if requested_case is not None and not selected_cases:
        raise SystemExit(f"Case {requested_case} is not a wire-testable Wireloom positive case.")

    by_idl = {Path(item["idl"]).name: item["id"] for item in selected_cases}
    candidates: dict[str, list[dict[str, str]]] = {case_id: [] for case_id in by_idl.values()}

    for source in generated_root.rglob("*.g.cs"):
        text = source.read_text(encoding="utf-8")
        header = re.search(r"generated by Wireloom from '([^']+)'", text)
        namespace = re.search(r"^namespace\s+([\w.]+)\s*;", text, re.MULTILINE)
        support = re.search(r"class\s+\w+\s*:\s*TypeSupport<\s*([\w.]+)\s*>", text)
        if not header or not support:
            continue

        case_id = by_idl.get(header.group(1))
        if case_id is None:
            continue

        type_name = support.group(1)
        if namespace and "." not in type_name:
            type_name = f"{namespace.group(1)}.{type_name}"
        candidates[case_id].append({
            "csharpType": type_name,
            "cppType": "::" + type_name.replace(".", "::"),
        })

    cases = []
    for case in selected_cases:
        found = candidates[case["id"]]
        if not found:
            raise SystemExit(f"No generated type support found for positive case {case['id']}.")

        preferred_types = {"Sample": 0, "Composed": 1}
        if case["id"] == "03-enums-aliases":
            preferred_types["Record"] = -1
        if case["id"] == "02-multiple":
            preferred_types["WireloomWireCompatibilityMultipleTypes"] = -1
        if case["id"] in {"03-enum-values-prefix", "03-enum-values-explicit"}:
            preferred_types["EnumTopic"] = -1
        if case["id"] == "07-union-aliases":
            preferred_types["Holder"] = -1
        if case["id"] == "08-key-inherited":
            preferred_types["Derived"] = -1
        if case["id"] == "08-key-nested":
            preferred_types["Outer"] = -1
        found.sort(key=lambda item: (
            preferred_types.get(item["csharpType"].rsplit(".", 1)[-1], 2),
            item["csharpType"],
        ))
        cases.append({"id": case["id"], **found[0]})

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps({"cases": cases}, indent=2) + "\n", encoding="utf-8")
    print(f"Discovered {len(cases)} Wireloom positive case type(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
