// <auto-generated/>
// This file was generated by Wireloom from '07-union-wchar-label.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;

namespace CorpusWideCharacterUnion.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Choice"/>.
/// </summary>
public struct ChoiceUnmanaged : INativeTopicType<Choice>
{
    private short _discriminator;

    private int letter;
    private NativeString text;
    private byte other;

    /// <summary>
    /// Releases native resources held by this union.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        text.Destroy();
    }

    /// <summary>
    /// Copies the active native union branch into a managed sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Choice sample, bool keysOnly = false)
    {
        switch ((char)_discriminator)
        {
            case 'a':
                sample.letter = letter;
                break;

            case 'z':
                sample.text = text.FromNative();
                break;

            default:
                sample.Setother(global::System.Convert.ToBoolean(other), (char)_discriminator);
                break;
        }
    }

    /// <summary>
    /// Initializes this native union representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        _discriminator = (short)Choice.DefaultDiscriminator;

        letter = 0;
        text.Initialize(size: 255, allocateMemory);

        other = 0;
    }

    /// <summary>
    /// Copies the active managed union branch into native storage.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Choice sample, bool keysOnly = false)
    {
        _discriminator = (short)sample.Discriminator;

        switch ((char)_discriminator)
        {
            case 'a':
                letter = sample.letter;
                break;

            case 'z':
                text.ToNative(sample.text, 255);
                break;

            default:
                other = global::System.Convert.ToByte(sample.other);
                break;
        }
    }
}
