// <auto-generated/>
// This file was generated by Wireloom from '07-union-scoped.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusScopedUnion;

/// <summary>
/// Represents the <c>Payload</c> DDS type declared in <c>07-union-scoped.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Payload : IEquatable<Payload>
{
    /// <summary>
    /// Gets or sets the <c>code</c> member.
    /// </summary>
    public int code { get; set; }

    /// <summary>
    /// Gets or sets the <c>label</c> member. Its maximum length is <c>16</c>.
    /// </summary>
    [Bound(16)]
    public string label { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Payload"/> class.
    /// </summary>
    public Payload()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Payload"/> class with the supplied member values.
    /// </summary>
    /// <param name="code">The value for the <c>code</c> member.</param>
    /// <param name="label">The value for the <c>label</c> member.</param>
    public Payload(int code, string label)
    {
        this.code = code;
        this.label = label;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Payload"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Payload(Payload? other)
    {
        if (other is null)
        {
            return;
        }

        code = other.code;
        label = other.label;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(code);
        hash.Add(label);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Payload? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return code.Equals(other.code)
            && label.Equals(other.label);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Payload);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => PayloadSupport.Instance.ToString(this);
}
