// <auto-generated/>
// This file was generated by Wireloom from '07-union-scoped.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusScopedUnion;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Payload"/>.
/// </summary>
public class PayloadSupport : TypeSupport<Payload>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PayloadSupport"/> class.
    /// </summary>
    public PayloadSupport() : base(
        new Implementation.PayloadPlugin(),
        new Lazy<DynamicType>(() => Implementation.PayloadPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static PayloadSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<PayloadSupport, Payload>();
}
