// <auto-generated/>
// This file was generated by Wireloom from '11-macro-operators.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusMacroOperators;

/// <summary>
/// Provides the <c>Name</c> IDL constant.
/// </summary>
public static class Name
{
    /// <summary>
    /// Gets the string value of the <c>Name</c> IDL constant.
    /// </summary>
    public const string Value = "sample";
}
