// <auto-generated/>
// This file was generated by Wireloom from '11-macro-operators.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusMacroOperators;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>11-macro-operators.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Sample : IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>field</c> member.
    /// </summary>
    public int field { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="field">The value for the <c>field</c> member.</param>
    public Sample(int field)
    {
        this.field = field;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        field = other.field;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(field);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return field.Equals(other.field);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
