// <auto-generated/>
// This file was generated by Wireloom from '08-key-union.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusUnionKeys.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Sample"/>.
/// </summary>
public struct SampleUnmanaged : INativeTopicType<Sample>
{
    private IdentityUnmanaged identity;
    private int payload;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        identity.Destroy(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Sample sample, bool keysOnly = false)
    {
        identity.FromNative(sample.identity, keysOnly: keysOnly);

        if (keysOnly)
        {
            return;
        }

        sample.payload = payload;
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        identity.Initialize(allocatePointers, allocateMemory);
        payload = 0;
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Sample sample, bool keysOnly = false)
    {
        identity.ToNative(sample.identity, keysOnly: keysOnly);

        if (keysOnly)
        {
            return;
        }

        payload = sample.payload;
    }
}
