// <auto-generated/>
// This file was generated by Wireloom from '08-key-union.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusUnionKeys;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Identity"/>.
/// </summary>
public class IdentitySupport : TypeSupport<Identity>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="IdentitySupport"/> class.
    /// </summary>
    public IdentitySupport() : base(
        new Implementation.IdentityPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.IdentityPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for this union.
    /// </summary>
    /// <remarks>Use this instance for generated type-support operations. The plugin and unmanaged representation are runtime implementation details.</remarks>
    public static IdentitySupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<IdentitySupport, Identity>();
}
