// <auto-generated/>
// This file was generated by Wireloom from '08-key-inherited.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusInheritedKeys;

/// <summary>
/// Represents the <c>Derived</c> DDS type declared in <c>08-key-inherited.idl</c>. Its key members form the DDS instance key. It derives from <see cref="Base"/>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Derived : Base, IEquatable<Derived>
{
    /// <summary>
    /// Gets or sets the <c>localId</c> member. This member forms part of the DDS instance key.
    /// </summary>
    [Key]
    public int localId { get; set; }

    /// <summary>
    /// Gets or sets the <c>payload</c> member.
    /// </summary>
    public int payload { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Derived"/> class.
    /// </summary>
    public Derived()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Derived"/> class with the supplied member values.
    /// </summary>
    /// <param name="tenant">The value for the <c>tenant</c> member.</param>
    /// <param name="baseValue">The value for the <c>baseValue</c> member.</param>
    /// <param name="localId">The value for the <c>localId</c> member.</param>
    /// <param name="payload">The value for the <c>payload</c> member.</param>
    public Derived(int tenant, int baseValue, int localId, int payload) : base(tenant, baseValue)
    {
        this.localId = localId;
        this.payload = payload;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Derived"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Derived(Derived? other) : base(other)
    {
        if (other is null)
        {
            return;
        }

        localId = other.localId;
        payload = other.payload;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(base.GetHashCode());
        hash.Add(localId);
        hash.Add(payload);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Derived? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        if (!base.Equals(other))
        {
            return false;
        }

        return localId.Equals(other.localId)
            && payload.Equals(other.payload);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Derived);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => DerivedSupport.Instance.ToString(this);
}
