// <auto-generated/>
// This file was generated by Wireloom from '08-key-inherited.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusInheritedKeys.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Derived"/>.
/// </summary>
internal class DerivedPlugin : InterpretedTypePlugin<Derived, DerivedUnmanaged>
{
    internal DerivedPlugin() : base("CorpusInheritedKeys.Derived", isKeyed: true, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Derived"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("localId", dtf.GetPrimitiveType<int>(), isKey: true, id: 2),
            new StructMember("payload", dtf.GetPrimitiveType<int>(), id: 3)
        };

        var result = tsf.CreateTypeWithAccessInfo<DerivedUnmanaged>(
            dtf.BuildStruct()
                .WithParent((StructType) BaseSupport.Instance.GetDynamicTypeInternal(isPublic))
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusInheritedKeys::Derived")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(1, annotations);
        }

        return result;
    }
}
