// <auto-generated/>
// This file was generated by Wireloom from '04-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusStringBoundaries;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>04-boundaries.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Sample : global::System.IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>narrow</c> member. Its maximum length is <c>8</c> characters.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this narrow IDL string counts characters. RTI encodes narrow IDL strings as UTF-8 by default. The generated C# property does not check the bound when assigned.</remarks>
    [Bound(8)]
    public string narrow { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the <c>wide</c> member. Its maximum length is <c>8</c> characters.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>The bound on this wide IDL string counts characters. RTI encodes wide IDL strings as UTF-16 by default. The generated C# property does not check the bound when assigned.</remarks>
    [Bound(8)]
    public string wide { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="narrow">The value for the <c>narrow</c> member.</param>
    /// <param name="wide">The value for the <c>wide</c> member.</param>
    public Sample(string narrow, string wide)
    {
        this.narrow = narrow;
        this.wide = wide;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Sample();
    /// var copy = new Sample(original);
    /// </code>
    /// </example>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        narrow = other.narrow;
        wide = other.wide;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(narrow);
        hash.Add(wide);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return narrow.Equals(other.narrow)
            && wide.Equals(other.wide);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
