// <auto-generated/>
// This file was generated by Wireloom from '02-constant-expressions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusConstantExpressions;

/// <summary>
/// Provides the <c>Masked</c> IDL constant.
/// </summary>
public static class Masked
{
    /// <summary>
    /// Gets the integer value of the <c>Masked</c> IDL constant.
    /// </summary>
    public const int Value = (Shifted.Value & 15) ^ 3;
}
