// <auto-generated/>
// This file was generated by Wireloom from '02-constant-expressions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusConstantExpressions;

/// <summary>
/// Provides the <c>Shifted</c> IDL constant.
/// </summary>
public static class Shifted
{
    /// <summary>
    /// Gets the integer value of the <c>Shifted</c> IDL constant.
    /// </summary>
    public const int Value = (Add.Value << 2) | 1;
}
