// <auto-generated/>
// This file was generated by Wireloom from '02-constant-expressions.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusConstantExpressions.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Sample"/>.
/// </summary>
internal class SamplePlugin : InterpretedTypePlugin<Sample, SampleUnmanaged>
{
    internal SamplePlugin() : base("CorpusConstantExpressions.Sample", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Sample"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("values", tsf.CreateSequenceWithAccessInfo(dtf, dtf.GetPrimitiveType<int>(), 5), id: 0),
            new StructMember("array", tsf.CreateArrayWithAccessInfo<int>(dtf, dtf.GetPrimitiveType<int>(), new uint[] { 5 }), id: 1)
        };

        var result = tsf.CreateTypeWithAccessInfo<SampleUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusConstantExpressions::Sample")
                .AddMembers(members));

        return result;
    }
}
