// <auto-generated/>
// This file was generated by Wireloom from '03-enum-values-explicit.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusEnumValues.Implementation;

/// <summary>
/// Provides the RTI runtime plugin for the <see cref="Explicit"/> enumeration. This implementation detail is not intended for application code.
/// </summary>
internal class ExplicitPlugin : EnumTypePlugin
{
    /// <summary>
    /// Initializes the RTI plugin for <see cref="Explicit"/>.
    /// </summary>
    internal ExplicitPlugin() : base(CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Explicit"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    internal static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var enumType = dtf.BuildEnum()
            .WithName("CorpusEnumValues::Explicit")
            .AddMember(new EnumMember("NEGATIVE", -2))
            .AddMember(new EnumMember("ZERO", 0))
            .AddMember(new EnumMember("GAP", 7))
            .AddMember(new EnumMember("NEXT", 8))
            .WithExtensibility(ExtensibilityKind.Extensible)
            .Create();

        {
            var annotations = new Annotations(
                TypeKind.Enumeration,
                defaultValue: new AnnotationParameterValue { EnumValue = -2 },
                minValue: null,
                maxValue: null,
                unit: null);
            enumType.SetAnnotations(annotations);
        }
        return enumType;
    }
}
