// <auto-generated/>
// This file was generated by Wireloom from '09-optional-aggregate-member.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusOptionalAggregate;

/// <summary>
/// Represents the <c>Choice</c> DDS union declared in <c>09-optional-aggregate-member.idl</c>. The discriminator selects a branch when it matches a declared label. If it matches no declared label, no branch is active.
/// </summary>
public partial class Choice : global::System.IEquatable<Choice>
{
    private Payload _payload = null!;
    private int _number;

    /// <summary>
    /// Gets the discriminator that selects the active DDS union branch.
    /// </summary>
    public int Discriminator { get; private set; }

    /// <summary>
    /// Gets the discriminator value used by the parameterless constructor.
    /// </summary>
    public const int DefaultDiscriminator = 0;

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>0</c>.
    /// </summary>
    /// <remarks>Reading this property while another branch is active throws <see cref="global::System.InvalidOperationException"/>. Assigning it stores the value and changes <see cref="Discriminator"/> to a label for this branch.</remarks>
    /// <exception cref="global::System.InvalidOperationException">The discriminator selects another branch or selects no branch.</exception>
    public Payload payload
    {
        get
        {
            if (Discriminator != 0)
            {
                throw new global::System.InvalidOperationException("payload not selected");
            }

            return _payload;
        }
        set
        {
            _payload = value;

            Discriminator = 0;
        }
    }

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>1</c>.
    /// </summary>
    /// <remarks>Reading this property while another branch is active throws <see cref="global::System.InvalidOperationException"/>. Assigning it stores the value and changes <see cref="Discriminator"/> to a label for this branch.</remarks>
    /// <exception cref="global::System.InvalidOperationException">The discriminator selects another branch or selects no branch.</exception>
    public int number
    {
        get
        {
            if (Discriminator != 1)
            {
                throw new global::System.InvalidOperationException("number not selected");
            }

            return _number;
        }
        set
        {
            _number = value;

            Discriminator = 1;
        }
    }

    /// <summary>
    /// Initializes a new union with its RTI default discriminator. If the default discriminator matches no declared label, no branch is active.
    /// </summary>
    public Choice()
    {
        Discriminator = DefaultDiscriminator;

        _payload = new Payload();
    }

    /// <summary>
    /// Initializes a copy of another <see cref="Choice"/> union.
    /// </summary>
    /// <param name="other">The union to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor leaves the discriminator at its default and does not copy a branch value.</remarks>
    public Choice(Choice? other)
    {
        if (other is null)
        {
            return;
        }

        Discriminator = other.Discriminator;

        switch (Discriminator)
        {
            case 0:
                this._payload = new Payload(other.payload);
                break;
            case 1:
                this._number = other.number;
                break;
        }
    }

    /// <summary>
    /// Gets the value of the currently active union branch, if any.
    /// </summary>
    /// <returns>The concrete value of the active branch, or <see langword="null"/> when the discriminator selects no declared branch.</returns>
    public object? Get()
    {
        return Discriminator switch
        {
            0 => payload,
            1 => number,
            _ => null,
        };
    }

    /// <summary>
    /// Computes a hash from the discriminator and, when a branch is active, its value.
    /// </summary>
    public override int GetHashCode()
    {
        return Discriminator switch
        {
            0 => global::System.HashCode.Combine(Discriminator, payload),
            1 => global::System.HashCode.Combine(Discriminator, number),
            _ => global::System.HashCode.Combine(Discriminator),
        };
    }

    /// <summary>
    /// Determines whether this union has the same discriminator and active branch value as <paramref name="other"/>. When neither discriminator selects a branch, equality depends on the discriminator alone.
    /// </summary>
    /// <param name="other">The union to compare.</param>
    /// <returns><see langword="true"/> when both unions select equal values; otherwise <see langword="false"/>.</returns>
    public bool Equals(Choice? other)
    {
        if (other is null || Discriminator != other.Discriminator)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Discriminator switch
        {
            0 => payload.Equals(other.payload),
            1 => number.Equals(other.number),
            _ => true,
        };
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Choice);

    /// <summary>
    /// Formats this union as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the union's type-support instance.</returns>
    public override string ToString() => ChoiceSupport.Instance.ToString(this);
}
