// <auto-generated/>
// This file was generated by Wireloom from '09-optional-aggregate-member.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusOptionalAggregate;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="PayloadAlias"/>.
/// </summary>
public class PayloadAliasSupport : TypeSupport<PayloadAlias>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PayloadAliasSupport"/> class.
    /// </summary>
    public PayloadAliasSupport() : base(
        new Implementation.PayloadAliasPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.PayloadAliasPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for formatting, serialization, and dynamic-type utilities for this typedef.
    /// </summary>
    /// <remarks>The generated plugin and unmanaged type are runtime implementation details; application code should use this support class and the managed typedef.</remarks>
    public static PayloadAliasSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<PayloadAliasSupport, PayloadAlias>();
}
