// <auto-generated/>
// This file was generated by Wireloom from '09-optional-aggregate-member.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusOptionalAggregate;

/// <summary>
/// Represents the <c>Payload</c> DDS type declared in <c>09-optional-aggregate-member.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Payload : global::System.IEquatable<Payload>
{
    /// <summary>
    /// Gets or sets the <c>value</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>.
    /// </summary>
    public int value { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Payload"/> class.
    /// </summary>
    public Payload()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Payload"/> class with the supplied member values.
    /// </summary>
    /// <param name="value">The value for the <c>value</c> member.</param>
    public Payload(int value)
    {
        this.value = value;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Payload"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Payload();
    /// var copy = new Payload(original);
    /// </code>
    /// </example>
    public Payload(Payload? other)
    {
        if (other is null)
        {
            return;
        }

        value = other.value;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Payload? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return value.Equals(other.value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Payload);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => PayloadSupport.Instance.ToString(this);
}
