// <auto-generated/>
// This file was generated by Wireloom from '09-optional-aggregate-member.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusOptionalAggregate;

/// <summary>
/// Represents the <c>PayloadAlias</c> IDL typedef declared in <c>09-optional-aggregate-member.idl</c>.
/// </summary>
public partial class PayloadAlias : global::System.IEquatable<PayloadAlias>
{
    /// <summary>
    /// Gets or sets the value represented by this typedef.
    /// </summary>
    public Payload Value { get; set; } = null!;

    /// <summary>
    /// Initializes the typedef value to its default value.
    /// </summary>
    public PayloadAlias()
    {
        Value = new Payload();
    }

    /// <summary>
    /// Initializes the typedef with a value.
    /// </summary>
    /// <param name="value">The value to store.</param>
    /// <remarks>The constructor stores the supplied reference as provided; it does not make a copy.</remarks>
    public PayloadAlias(Payload value)
    {
        Value = value;
    }

    /// <summary>
    /// Initializes a copy of another typedef value.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor returns without copying and keeps its property initializer. An aggregate value is copied through its generated copy constructor.</remarks>
    public PayloadAlias(PayloadAlias? other)
    {
        if (other is not null)
        {
            Value = new Payload(other.Value);
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(Value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    /// <returns><see langword="true"/> when both typedefs have equal values; otherwise, <see langword="false"/>.</returns>
    public bool Equals(PayloadAlias? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as PayloadAlias);

    /// <summary>
    /// Formats this typedef as readable text.
    /// </summary>
    /// <returns>A readable string formatted by this typedef's type-support instance.</returns>
    public override string ToString() => PayloadAliasSupport.Instance.ToString(this);
}
