// <auto-generated/>
// This file was generated by Wireloom from '07-duplicate-label.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusNegativeDuplicateLabel.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Choice"/>.
/// </summary>
public struct ChoiceUnmanaged : INativeTopicType<Choice>
{
    private int _discriminator;

    private int first;
    private int second;

    /// <summary>
    /// Releases native resources held by this union.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }
    }

    /// <summary>
    /// Copies the active native union branch into a managed sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Choice sample, bool keysOnly = false)
    {
        switch (_discriminator)
        {
            case 1:
                sample.first = first;
                break;

            case 1:
                sample.second = second;
                break;

            default:
                break;
        }
    }

    /// <summary>
    /// Initializes this native union representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        _discriminator = Choice.DefaultDiscriminator;

        first = 0;

        second = 0;
    }

    /// <summary>
    /// Copies the active managed union branch into native storage.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Choice sample, bool keysOnly = false)
    {
        _discriminator = sample.Discriminator;

        switch (_discriminator)
        {
            case 1:
                first = sample.first;
                break;

            case 1:
                second = sample.second;
                break;

            default:
                break;
        }
    }
}
