// <auto-generated/>
// This file was generated by Wireloom from '10-annotations-extended.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusAnnotationVariants;

/// <summary>
/// Provides application-facing formatting, serialization, and dynamic-type utilities for <see cref="Sample"/>. RTI uses its internal plugin and native representation to process samples.
/// </summary>
/// <remarks>The referenced API documentation targets RTI Connext 7.7.0, Wireloom's current compatibility baseline. Verify API details against the runtime version used by the consuming project.</remarks>
/// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/api/connext_dds/api_csharp/classRti_1_1Dds_1_1Topics_1_1TypeSupport.html">RTI Connext C# TypeSupport API (7.7.0)</seealso>
/// <example>
/// <code>
/// var sample = new Sample();
/// var text = SampleSupport.Instance.ToString(sample);
/// var dynamicType = SampleSupport.Instance.DynamicType;
/// var serializer = SampleSupport.Instance.CreateSerializer();
/// </code>
/// </example>
public class SampleSupport : TypeSupport<Sample>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="SampleSupport"/> class.
    /// </summary>
    public SampleSupport() : base(
        new Implementation.SamplePlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.SamplePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance used by the generated utilities and DDS APIs for this type.
    /// </summary>
    /// <remarks>Use this property to format or serialize samples and to inspect the dynamic type. The generated plugin and unmanaged type are runtime implementation details.</remarks>
    public static SampleSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<SampleSupport, Sample>();
}
