// <auto-generated/>
// This file was generated by Wireloom from '07-union-multilabel.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusMultiLabelUnion.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Choice"/>.
/// </summary>
internal class ChoicePlugin : InterpretedTypePlugin<Choice, ChoiceUnmanaged>
{
    internal ChoicePlugin() : base("CorpusMultiLabelUnion.Choice", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Choice"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new UnionMember[]
        {
            new UnionMember("number", dtf.GetPrimitiveType<int>(), new int[] { 1, 5 }, id: 1),
            new UnionMember("text", dtf.CreateString(255), new int[] { 2 }, id: 2)
        };

        var result = tsf.CreateTypeWithAccessInfo<ChoiceUnmanaged>(
            dtf.BuildUnion()
                .WithDiscriminator(dtf.GetPrimitiveType<int>())
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusMultiLabelUnion::Choice")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.String,
                defaultValue: new AnnotationParameterValue { StringValue = "" },
                minValue: null,
                maxValue: null,
                unit: null);
            result.SetMemberAnnotations(1, annotations);
        }

        return result;
    }
}
