// <auto-generated/>
// This file was generated by Wireloom from '07-union-multilabel.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusMultiLabelUnion;

/// <summary>
/// Represents the <c>Choice</c> DDS union declared in <c>07-union-multilabel.idl</c>. The discriminator selects a branch when it matches a declared label; otherwise, no branch is active.
/// </summary>
public partial class Choice : global::System.IEquatable<Choice>
{
    private int _number;
    private string _text = string.Empty;

    /// <summary>
    /// Gets the discriminator that selects the active DDS union branch.
    /// </summary>
    public int Discriminator { get; private set; }

    /// <summary>
    /// Gets the discriminator value used by the parameterless constructor.
    /// </summary>
    public const int DefaultDiscriminator = 0;

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>1, 5</c>.
    /// </summary>
    /// <remarks>Reading this property while another branch is active throws <see cref="global::System.InvalidOperationException"/>. Assigning it stores the value and changes <see cref="Discriminator"/> to a label for this branch.</remarks>
    /// <exception cref="global::System.InvalidOperationException">The discriminator selects another branch or selects no branch.</exception>
    public int number
    {
        get
        {
            if (Discriminator != 1 && Discriminator != 5)
            {
                throw new global::System.InvalidOperationException("number not selected");
            }

            return _number;
        }
        set
        {
            _number = value;

            Discriminator = 1;
        }
    }

    /// <summary>
    /// Sets the number branch with an explicit discriminator value.
    /// </summary>
    /// <param name="value">The value for the number branch.</param>
    /// <param name="discriminator">A discriminator value selecting this branch.</param>
    /// <remarks>Assigning the <c>number</c> property selects the first label listed in its documentation. Use this method to select another valid label for the same branch.</remarks>
    /// <example>
    /// <code>
    /// var choice = new Choice();
    /// choice.number = default!;
    /// choice.Setnumber(default!, 1);
    /// </code>
    /// </example>
    /// <exception cref="global::System.ArgumentException">The discriminator does not select this branch.</exception>
    public void Setnumber(int value, int discriminator)
    {
        if (!(discriminator == 1 || discriminator == 5))
        {
            throw new global::System.ArgumentException("Invalid discriminator value for number", nameof(discriminator));
        }

        _number = value;

        Discriminator = discriminator;
    }

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>2</c>.
    /// </summary>
    /// <remarks>Reading this property while another branch is active throws <see cref="global::System.InvalidOperationException"/>. Assigning it stores the value and changes <see cref="Discriminator"/> to a label for this branch.</remarks>
    /// <exception cref="global::System.InvalidOperationException">The discriminator selects another branch or selects no branch.</exception>
    [Bound(255)]
    public string text
    {
        get
        {
            if (Discriminator != 2)
            {
                throw new global::System.InvalidOperationException("text not selected");
            }

            return _text;
        }
        set
        {
            _text = value;

            Discriminator = 2;
        }
    }

    /// <summary>
    /// Initializes a new union with its RTI default discriminator. A branch is active only when that discriminator matches a declared label or selects the default branch.
    /// </summary>
    public Choice()
    {
        Discriminator = DefaultDiscriminator;
    }

    /// <summary>
    /// Initializes a copy of another <see cref="Choice"/> union.
    /// </summary>
    /// <param name="other">The union to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor leaves the discriminator at its default and does not copy a branch value.</remarks>
    public Choice(Choice? other)
    {
        if (other is null)
        {
            return;
        }

        Discriminator = other.Discriminator;

        switch (Discriminator)
        {
            case 1:
            case 5:
                this._number = other.number;
                break;
            case 2:
                this._text = other.text;
                break;
            default:
                break;
        }
    }

    /// <summary>
    /// Gets the value of the currently active union branch, if any.
    /// </summary>
    /// <returns>The concrete value of the active branch, or <see langword="null"/> when the discriminator selects no declared branch.</returns>
    public object? Get()
    {
        return Discriminator switch
        {
            1 or 5 => number,
            2 => text,
            _ => null,
        };
    }

    /// <summary>
    /// Computes a hash from the discriminator and, when a branch is active, its value.
    /// </summary>
    public override int GetHashCode()
    {
        return Discriminator switch
        {
            1 or 5 => global::System.HashCode.Combine(Discriminator, number),
            2 => global::System.HashCode.Combine(Discriminator, text),
            _ => global::System.HashCode.Combine(Discriminator),
        };
    }

    /// <summary>
    /// Determines whether this union has the same discriminator and active branch value as <paramref name="other"/>. When neither discriminator selects a branch, equality depends on the discriminator alone.
    /// </summary>
    /// <param name="other">The union to compare.</param>
    /// <returns><see langword="true"/> when both unions select equal values; otherwise <see langword="false"/>.</returns>
    public bool Equals(Choice? other)
    {
        if (other is null || Discriminator != other.Discriminator)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Discriminator switch
        {
            1 or 5 => number.Equals(other.number),
            2 => text.Equals(other.text),
            _ => true,
        };
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Choice);

    /// <summary>
    /// Formats this union as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the union's type-support instance.</returns>
    public override string ToString() => ChoiceSupport.Instance.ToString(this);
}
