// <auto-generated/>
// This file was generated by Wireloom from '01-full-widths.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusFullWidths.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Sample"/>.
/// </summary>
internal class SamplePlugin : InterpretedTypePlugin<Sample, SampleUnmanaged>
{
    internal SamplePlugin() : base("CorpusFullWidths.Sample", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Sample"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("i8", dtf.GetPrimitiveType<sbyte>(), id: 0),
            new StructMember("i16", dtf.GetPrimitiveType<short>(), id: 1),
            new StructMember("i32", dtf.GetPrimitiveType<int>(), id: 2),
            new StructMember("i64", dtf.GetPrimitiveType<long>(), id: 3),
            new StructMember("u8", dtf.GetPrimitiveType<byte>(), id: 4),
            new StructMember("u16", dtf.GetPrimitiveType<ushort>(), id: 5),
            new StructMember("u32", dtf.GetPrimitiveType<uint>(), id: 6),
            new StructMember("u64", dtf.GetPrimitiveType<ulong>(), id: 7)
        };

        var result = tsf.CreateTypeWithAccessInfo<SampleUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusFullWidths::Sample")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int8,
                defaultValue: new AnnotationParameterValue { Int8Value = (sbyte)0 },
                minValue: new AnnotationParameterValue { Int8Value = sbyte.MinValue },
                maxValue: new AnnotationParameterValue { Int8Value = sbyte.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Int16,
                defaultValue: new AnnotationParameterValue { Int16Value = (short)0 },
                minValue: new AnnotationParameterValue { Int16Value = short.MinValue },
                maxValue: new AnnotationParameterValue { Int16Value = short.MaxValue },
                unit: null);
            result.SetMemberAnnotations(1, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(2, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Int64,
                defaultValue: new AnnotationParameterValue { Int64Value = 0L },
                minValue: new AnnotationParameterValue { Int64Value = long.MinValue },
                maxValue: new AnnotationParameterValue { Int64Value = long.MaxValue },
                unit: null);
            result.SetMemberAnnotations(3, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Uint8,
                defaultValue: new AnnotationParameterValue { Uint8Value = (byte)0 },
                minValue: new AnnotationParameterValue { Uint8Value = byte.MinValue },
                maxValue: new AnnotationParameterValue { Uint8Value = byte.MaxValue },
                unit: null);
            result.SetMemberAnnotations(4, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Uint16,
                defaultValue: new AnnotationParameterValue { Uint16Value = (ushort)0 },
                minValue: new AnnotationParameterValue { Uint16Value = ushort.MinValue },
                maxValue: new AnnotationParameterValue { Uint16Value = ushort.MaxValue },
                unit: null);
            result.SetMemberAnnotations(5, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.UInt32,
                defaultValue: new AnnotationParameterValue { Uint32Value = 0u },
                minValue: new AnnotationParameterValue { Uint32Value = uint.MinValue },
                maxValue: new AnnotationParameterValue { Uint32Value = uint.MaxValue },
                unit: null);
            result.SetMemberAnnotations(6, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.UInt64,
                defaultValue: new AnnotationParameterValue { Uint64Value = 0uL },
                minValue: new AnnotationParameterValue { Uint64Value = ulong.MinValue },
                maxValue: new AnnotationParameterValue { Uint64Value = ulong.MaxValue },
                unit: null);
            result.SetMemberAnnotations(7, annotations);
        }

        return result;
    }
}
