// <auto-generated/>
// This file was generated by Wireloom from '01-full-widths.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusFullWidths;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>01-full-widths.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Sample : global::System.IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>i8</c> member. Representable values are in the inclusive range <c>sbyte.MinValue</c> through <c>sbyte.MaxValue</c>.
    /// </summary>
    public sbyte i8 { get; set; }

    /// <summary>
    /// Gets or sets the <c>i16</c> member. Representable values are in the inclusive range <c>short.MinValue</c> through <c>short.MaxValue</c>.
    /// </summary>
    public short i16 { get; set; }

    /// <summary>
    /// Gets or sets the <c>i32</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>.
    /// </summary>
    public int i32 { get; set; }

    /// <summary>
    /// Gets or sets the <c>i64</c> member. Representable values are in the inclusive range <c>long.MinValue</c> through <c>long.MaxValue</c>.
    /// </summary>
    public long i64 { get; set; }

    /// <summary>
    /// Gets or sets the <c>u8</c> member. Representable values are in the inclusive range <c>byte.MinValue</c> through <c>byte.MaxValue</c>.
    /// </summary>
    public byte u8 { get; set; }

    /// <summary>
    /// Gets or sets the <c>u16</c> member. Representable values are in the inclusive range <c>ushort.MinValue</c> through <c>ushort.MaxValue</c>.
    /// </summary>
    public ushort u16 { get; set; }

    /// <summary>
    /// Gets or sets the <c>u32</c> member. Representable values are in the inclusive range <c>uint.MinValue</c> through <c>uint.MaxValue</c>.
    /// </summary>
    public uint u32 { get; set; }

    /// <summary>
    /// Gets or sets the <c>u64</c> member. Representable values are in the inclusive range <c>ulong.MinValue</c> through <c>ulong.MaxValue</c>.
    /// </summary>
    public ulong u64 { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="i8">The value for the <c>i8</c> member.</param>
    /// <param name="i16">The value for the <c>i16</c> member.</param>
    /// <param name="i32">The value for the <c>i32</c> member.</param>
    /// <param name="i64">The value for the <c>i64</c> member.</param>
    /// <param name="u8">The value for the <c>u8</c> member.</param>
    /// <param name="u16">The value for the <c>u16</c> member.</param>
    /// <param name="u32">The value for the <c>u32</c> member.</param>
    /// <param name="u64">The value for the <c>u64</c> member.</param>
    public Sample(sbyte i8, short i16, int i32, long i64, byte u8, ushort u16, uint u32, ulong u64)
    {
        this.i8 = i8;
        this.i16 = i16;
        this.i32 = i32;
        this.i64 = i64;
        this.u8 = u8;
        this.u16 = u16;
        this.u32 = u32;
        this.u64 = u64;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Sample();
    /// var copy = new Sample(original);
    /// </code>
    /// </example>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        i8 = other.i8;
        i16 = other.i16;
        i32 = other.i32;
        i64 = other.i64;
        u8 = other.u8;
        u16 = other.u16;
        u32 = other.u32;
        u64 = other.u64;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(i8);
        hash.Add(i16);
        hash.Add(i32);
        hash.Add(i64);
        hash.Add(u8);
        hash.Add(u16);
        hash.Add(u32);
        hash.Add(u64);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return i8.Equals(other.i8)
            && i16.Equals(other.i16)
            && i32.Equals(other.i32)
            && i64.Equals(other.i64)
            && u8.Equals(other.u8)
            && u16.Equals(other.u16)
            && u32.Equals(other.u32)
            && u64.Equals(other.u64);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
