// <auto-generated/>
// This file was generated by Wireloom from '08-key-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusKeyBoundaries;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="ArrayKey"/>.
/// </summary>
public class ArrayKeySupport : TypeSupport<ArrayKey>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ArrayKeySupport"/> class.
    /// </summary>
    public ArrayKeySupport() : base(
        new Implementation.ArrayKeyPlugin(),
        new Lazy<DynamicType>(() => Implementation.ArrayKeyPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static ArrayKeySupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ArrayKeySupport, ArrayKey>();
}
