// <auto-generated/>
// This file was generated by Wireloom from '08-key-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusKeyBoundaries.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="UnboundedStringKey"/>.
/// </summary>
internal class UnboundedStringKeyPlugin : InterpretedTypePlugin<UnboundedStringKey, UnboundedStringKeyUnmanaged>
{
    internal UnboundedStringKeyPlugin() : base("CorpusKeyBoundaries.UnboundedStringKey", isKeyed: true, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="UnboundedStringKey"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("name", dtf.CreateString(255), isKey: true, id: 0),
            new StructMember("payload", dtf.GetPrimitiveType<int>(), id: 1)
        };

        var result = tsf.CreateTypeWithAccessInfo<UnboundedStringKeyUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusKeyBoundaries::UnboundedStringKey")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.String,
                defaultValue: new AnnotationParameterValue { StringValue = "" },
                minValue: null,
                maxValue: null,
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(1, annotations);
        }

        return result;
    }
}
