// <auto-generated/>
// This file was generated by Wireloom from '08-key-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;

namespace CorpusKeyBoundaries.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="ArrayKey"/>.
/// </summary>
public struct ArrayKeyUnmanaged : INativeTopicType<ArrayKey>
{
    private NativeUnmanagedArray coordinates;
    private int payload;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    /// <remarks>This method releases resources owned by the generated native representation. Pass <see langword="true"/> to release optional members only, or <see langword="false"/> to release all members.</remarks>
    public void Destroy(bool optionalsOnly)
    {
        coordinates.Destroy(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">When the type has key members, whether to copy only those members.</param>
    /// <remarks>The operation copies values into <paramref name="sample"/>. When <paramref name="keysOnly"/> is true, only key members are copied.</remarks>
    public void FromNative(ArrayKey sample, bool keysOnly = false)
    {
        coordinates.FromNative(sample.coordinates, dimension: 2);

        if (keysOnly)
        {
            return;
        }

        sample.payload = payload;
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    /// <remarks>Use this method to prepare native storage before conversion. Call <see cref="Destroy"/> when the native representation is no longer needed.</remarks>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        coordinates.Initialize<int>(dimension: 2, allocateMemory);
        payload = 0;
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">When the type has key members, whether to copy only those members.</param>
    /// <remarks>The operation copies values from <paramref name="sample"/> into native storage. When <paramref name="keysOnly"/> is true, only key members are copied.</remarks>
    public void ToNative(ArrayKey sample, bool keysOnly = false)
    {
        coordinates.ToNative(sample.coordinates, dimension: 2);

        if (keysOnly)
        {
            return;
        }

        payload = sample.payload;
    }
}
