// <auto-generated/>
// This file was generated by Wireloom from '08-key-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusKeyBoundaries;

/// <summary>
/// Represents the <c>UnboundedStringKey</c> DDS type declared in <c>08-key-boundaries.idl</c>. Its key members form the DDS instance key. It is marked as <c>extensible</c>.
/// </summary>
public partial class UnboundedStringKey : IEquatable<UnboundedStringKey>
{
    /// <summary>
    /// Gets or sets the <c>name</c> member. This member forms part of the DDS instance key. Its maximum length is <c>255</c>.
    /// </summary>
    [Key]
    [Bound(255)]
    public string name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the <c>payload</c> member.
    /// </summary>
    public int payload { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="UnboundedStringKey"/> class.
    /// </summary>
    public UnboundedStringKey()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="UnboundedStringKey"/> class with the supplied member values.
    /// </summary>
    /// <param name="name">The value for the <c>name</c> member.</param>
    /// <param name="payload">The value for the <c>payload</c> member.</param>
    public UnboundedStringKey(string name, int payload)
    {
        this.name = name;
        this.payload = payload;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="UnboundedStringKey"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public UnboundedStringKey(UnboundedStringKey? other)
    {
        if (other is null)
        {
            return;
        }

        name = other.name;
        payload = other.payload;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(name);
        hash.Add(payload);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(UnboundedStringKey? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return name.Equals(other.name)
            && payload.Equals(other.payload);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as UnboundedStringKey);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => UnboundedStringKeySupport.Instance.ToString(this);
}
