// <auto-generated/>
// This file was generated by Wireloom from '08-key-boundaries.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusKeyBoundaries;

/// <summary>
/// Represents the <c>ArrayKey</c> DDS type declared in <c>08-key-boundaries.idl</c>. Its key members form the DDS instance key. It is marked as <c>extensible</c>.
/// </summary>
public partial class ArrayKey : IEquatable<ArrayKey>
{
    /// <summary>
    /// Gets or sets the <c>coordinates</c> member. This member forms part of the DDS instance key.
    /// </summary>
    [Key]
    public int[] coordinates { get; set; } = null!;

    /// <summary>
    /// Gets or sets the <c>payload</c> member.
    /// </summary>
    public int payload { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ArrayKey"/> class.
    /// </summary>
    public ArrayKey()
    {
        coordinates = new int[2];
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ArrayKey"/> class with the supplied member values.
    /// </summary>
    /// <param name="coordinates">The value for the <c>coordinates</c> member.</param>
    /// <param name="payload">The value for the <c>payload</c> member.</param>
    public ArrayKey(int[] coordinates, int payload)
    {
        this.coordinates = coordinates;
        this.payload = payload;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="ArrayKey"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public ArrayKey(ArrayKey? other)
    {
        if (other is null)
        {
            return;
        }

        coordinates = (int[])other.coordinates.Clone();
        payload = other.payload;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(coordinates[0]);
        hash.Add(payload);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(ArrayKey? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return coordinates.SequenceEqual(other.coordinates)
            && payload.Equals(other.payload);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as ArrayKey);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => ArrayKeySupport.Instance.ToString(this);
}
