// <auto-generated/>
// This file was generated by Wireloom from '03-enum-values-prefix.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusEnumValuePrefix.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Annotated"/>.
/// </summary>
internal class AnnotatedPlugin : EnumTypePlugin
{
    internal AnnotatedPlugin() : base(CreateDynamicType(isPublic: false))
    {
    }

    internal static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var enumType = dtf.BuildEnum()
            .WithName("CorpusEnumValuePrefix::Annotated")
            .AddMember(new EnumMember("FIRST", 7))
            .AddMember(new EnumMember("SECOND", 8))
            .WithExtensibility(ExtensibilityKind.Extensible)
            .Create();

        {
            var annotations = new Annotations(
                TypeKind.Enumeration,
                defaultValue: new AnnotationParameterValue { EnumValue = 7 },
                minValue: null,
                maxValue: null,
                unit: null);
            enumType.SetAnnotations(annotations);
        }
        return enumType;
    }
}
