// <auto-generated/>
// This file was generated by Wireloom from '05-array-of-sequences.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusArrayOfSequences.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Sample"/>.
/// </summary>
public struct SampleUnmanaged : INativeTopicType<Sample>
{
    private NativeSeq values;
    private NativeStringSeq names;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        values.Destroy(optionalsOnly);
        names.Destroy();
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Sample sample, bool keysOnly = false)
    {
        values.FromNative((Sequence<int>)sample.values);
        names.FromNative(sample.names);
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        values.Initialize<int>(max: 100, absoluteMax: 100, allocateMemory: allocateMemory);
        names.Initialize(max: 3, absoluteMax: 3, maxStrLen: 16, allocateMemory: allocateMemory);
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Sample sample, bool keysOnly = false)
    {
        values.ToNative((Sequence<int>)sample.values);
        names.ToNative(sample.names, 16);
    }
}
