// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusEnums.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Record"/>.
/// </summary>
public struct RecordUnmanaged : INativeTopicType<Record>
{
    private int value;
    private int aliasValue;
    private Color color;
    private Color aliasColor;
    private ColorSequenceUnmanaged colors;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        colors.Destroy(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed DDS sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Record sample, bool keysOnly = false)
    {
        sample.value = value;
        sample.aliasValue = aliasValue;
        sample.color = color;
        sample.aliasColor = aliasColor;
        colors.FromNative(sample.colors, keysOnly: false);
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        value = 0;
        aliasValue = 0;
        color = (Color)0;
        aliasColor = (Color)0;
        colors.Initialize(allocatePointers, allocateMemory);
    }

    /// <summary>
    /// Copies a managed DDS sample into this native representation.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Record sample, bool keysOnly = false)
    {
        value = sample.value;
        aliasValue = sample.aliasValue;
        color = sample.color;
        aliasColor = sample.aliasColor;
        colors.ToNative(sample.colors, keysOnly: false);
    }
}
