// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusEnums;

/// <summary>
/// Represents the <c>ScalarAlias</c> IDL typedef declared in <c>03-enums-aliases.idl</c>.
/// </summary>
public partial class ScalarAlias : IEquatable<ScalarAlias>
{
    /// <summary>
    /// Gets or sets the value represented by this typedef.
    /// </summary>
    public int Value { get; set; }

    /// <summary>
    /// Initializes an empty typedef value.
    /// </summary>
    public ScalarAlias()
    {
    }

    /// <summary>
    /// Initializes the typedef with a value.
    /// </summary>
    /// <param name="Value">The value to store.</param>
    public ScalarAlias(int Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another typedef value.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    public ScalarAlias(ScalarAlias? other)
    {
        if (other is not null)
        {
            Value = other.Value;
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(Value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    public bool Equals(ScalarAlias? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as ScalarAlias);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this typedef.
    /// </summary>
    public override string ToString() => ScalarAliasSupport.Instance.ToString(this);
}
