// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusEnums.Implementation;

public struct ScalarAliasUnmanaged : INativeTopicType<ScalarAlias>
{
    private int Value;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
    }

    /// <summary>
    /// Copies native values into a managed typedef sample.
    /// </summary>
    /// <param name="sample">The managed typedef to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(ScalarAlias sample, bool keysOnly = false)
    {
        sample.Value = Value;
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        Value = (int)0;
    }

    /// <summary>
    /// Copies a managed typedef sample into native storage.
    /// </summary>
    /// <param name="sample">The managed typedef to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(ScalarAlias sample, bool keysOnly = false)
    {
        Value = sample.Value;
    }
}
