// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusEnums;

/// <summary>
/// Represents the <c>Scalar</c> IDL typedef declared in <c>03-enums-aliases.idl</c>.
/// </summary>
public partial class Scalar : global::System.IEquatable<Scalar>
{
    /// <summary>
    /// Gets or sets the value represented by this typedef.
    /// </summary>
    public int Value { get; set; }

    /// <summary>
    /// Initializes the typedef value to its default value.
    /// </summary>
    public Scalar()
    {
    }

    /// <summary>
    /// Initializes the typedef with a value.
    /// </summary>
    /// <param name="value">The value to store.</param>
    public Scalar(int value)
    {
        Value = value;
    }

    /// <summary>
    /// Initializes a copy of another typedef value.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    /// <remarks>When <paramref name="other"/> is null, the constructor returns without copying and keeps its property initializer. An aggregate value is copied through its generated copy constructor.</remarks>
    public Scalar(Scalar? other)
    {
        if (other is not null)
        {
            Value = other.Value;
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(Value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this typedef has the same value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    /// <returns><see langword="true"/> when both typedefs have equal values; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Scalar? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Scalar);

    /// <summary>
    /// Formats this typedef as readable text.
    /// </summary>
    /// <returns>A readable string formatted by this typedef's type-support instance.</returns>
    public override string ToString() => ScalarSupport.Instance.ToString(this);
}
