// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusEnums;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Record"/>.
/// </summary>
public class RecordSupport : TypeSupport<Record>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="RecordSupport"/> class.
    /// </summary>
    public RecordSupport() : base(
        new Implementation.RecordPlugin(),
        new Lazy<DynamicType>(() => Implementation.RecordPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static RecordSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<RecordSupport, Record>();
}
