// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusEnums;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="ColorAlias2"/>.
/// </summary>
public class ColorAlias2Support : TypeSupport<ColorAlias2>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ColorAlias2Support"/> class.
    /// </summary>
    public ColorAlias2Support() : base(
        new Implementation.ColorAlias2Plugin(),
        new Lazy<DynamicType>(() => Implementation.ColorAlias2Plugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static ColorAlias2Support Instance { get; } = ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ColorAlias2Support, ColorAlias2>();
}
