// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusEnums;

/// <summary>
/// Represents the <c>ColorSequence</c> IDL typedef declared in <c>03-enums-aliases.idl</c>.
/// </summary>
public partial class ColorSequence : IEquatable<ColorSequence>
{
    /// <summary>
    /// Gets the sequence value represented by this typedef. Its maximum number of elements is <c>3</c>.
    /// </summary>
    [Bound(3)]
    public ISequence<Color> Value { get; } = null!;

    /// <summary>
    /// Initializes an empty sequence typedef.
    /// </summary>
    public ColorSequence()
    {
        Value = new Sequence<Color>();
    }

    /// <summary>
    /// Initializes the typedef with a sequence value.
    /// </summary>
    /// <param name="Value">The sequence value to store.</param>
    public ColorSequence(ISequence<Color> Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another sequence typedef.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    public ColorSequence(ColorSequence? other)
    {
        if (other is null)
        {
            return;
        }

        Value = new Sequence<Color>(other.Value);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Value.Count;
    }

    /// <summary>
    /// Determines whether this typedef has the same sequence values as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    public bool Equals(ColorSequence? other)
    {
        return other is not null
            && (ReferenceEquals(this, other) || Value.SequenceEqual(other.Value));
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as ColorSequence);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this typedef.
    /// </summary>
    public override string ToString() => ColorSequenceSupport.Instance.ToString(this);
}
