// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusEnums;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="ColorSequence"/>.
/// </summary>
public class ColorSequenceSupport : TypeSupport<ColorSequence>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ColorSequenceSupport"/> class.
    /// </summary>
    public ColorSequenceSupport() : base(
        new Implementation.ColorSequencePlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.ColorSequencePlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for formatting, serialization, and dynamic-type utilities for this typedef.
    /// </summary>
    /// <remarks>The generated plugin and unmanaged type are runtime implementation details; application code should use this support class and the managed typedef.</remarks>
    public static ColorSequenceSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<ColorSequenceSupport, ColorSequence>();
}
