// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types.Dynamic;

namespace CorpusEnums.Implementation;

/// <summary>
/// Provides the RTI runtime plugin for the ColorSequence typedef. This implementation detail is not intended for application code.
/// </summary>
internal class ColorSequencePlugin : InterpretedTypePlugin<ColorSequence, ColorSequenceUnmanaged>
{
    /// <summary>
    /// Initializes the RTI plugin for <see cref="ColorSequence"/>.
    /// </summary>
    internal ColorSequencePlugin() : base("CorpusEnums.ColorSequence", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="ColorSequence"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        return tsf.CreateAliasWithAccessInfo<ColorSequenceUnmanaged>(dtf, "ColorSequence", tsf.CreateSequenceWithAccessInfo(dtf, ColorSupport.Instance.GetDynamicTypeInternal(isPublic), 3));
    }
}
