// <auto-generated/>
// This file was generated by Wireloom from '03-enums-aliases.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using System;

namespace CorpusEnums;

/// <summary>
/// Represents the <c>Color</c> enumeration declared in <c>03-enums-aliases.idl</c>.
/// </summary>
public enum Color
{
    /// <summary>
    /// The <c>RED</c> enumeration value.
    /// </summary>
    RED,

    /// <summary>
    /// The <c>GREEN</c> enumeration value.
    /// </summary>
    GREEN,

    /// <summary>
    /// The <c>BLUE</c> enumeration value.
    /// </summary>
    BLUE,
}
