// <auto-generated/>
// This file was generated by Wireloom from '06-valuetypes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types.Dynamic;

namespace CorpusValueTypes.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="BaseValue"/>.
/// </summary>
internal class BaseValuePlugin : InterpretedTypePlugin<BaseValue, BaseValueUnmanaged>
{
    /// <summary>
    /// Initializes the RTI plugin for <see cref="BaseValue"/>.
    /// </summary>
    internal BaseValuePlugin() : base("CorpusValueTypes.BaseValue", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="BaseValue"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new[]
        {
            new StructMember("baseValue", dtf.GetPrimitiveType<int>(), id: 0)
        };

        var result = tsf.CreateTypeWithAccessInfo<BaseValueUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusValueTypes::BaseValue")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        return result;
    }
}
