// <auto-generated/>
// This file was generated by Wireloom from '11-include-search.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusIncludeSearch;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>11-include-search.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Sample : global::System.IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>item</c> member.
    /// </summary>
    public global::IncludedType item { get; set; } = new global::IncludedType();

    /// <summary>
    /// Gets or sets the <c>value</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>.
    /// </summary>
    public int value { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    /// <remarks>nested aggregate members start as new instances.</remarks>
    public Sample()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="item">The value for the <c>item</c> member.</param>
    /// <param name="value">The value for the <c>value</c> member.</param>
    /// <remarks>The constructor stores supplied reference-type member values as provided. It does not clone their arrays, sequences, or nested objects.</remarks>
    public Sample(global::IncludedType item, int value)
    {
        this.item = item;
        this.value = value;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Sample();
    /// var copy = new Sample(original);
    /// </code>
    /// </example>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        item = new global::IncludedType(other.item);
        value = other.value;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(item);
        hash.Add(value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return item.Equals(other.item)
            && value.Equals(other.value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
