// <auto-generated/>
// This file was generated by Wireloom from '10-annotations.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusAnnotations;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>10-annotations.idl</c>. Its key members form the DDS instance key. It is marked as <c>extensible</c>. It is marked as a DDS topic type.
/// </summary>
public partial class Sample : IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>id</c> member. This member forms part of the DDS instance key.
    /// </summary>
    [Key]
    public int id { get; set; }

    /// <summary>
    /// Gets or sets the <c>value</c> member. Its default value is <c>3</c>.
    /// </summary>
    public int value { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
        value = 3;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="id">The value for the <c>id</c> member.</param>
    /// <param name="value">The value for the <c>value</c> member.</param>
    public Sample(int id, int value)
    {
        this.id = id;
        this.value = value;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        id = other.id;
        value = other.value;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(id);
        hash.Add(value);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return id.Equals(other.id)
            && value.Equals(other.value);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
