// <auto-generated/>
// This file was generated by Wireloom from '05-shapes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusCollectionShapes;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Names"/>.
/// </summary>
public class NamesSupport : TypeSupport<Names>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="NamesSupport"/> class.
    /// </summary>
    public NamesSupport() : base(
        new Implementation.NamesPlugin(),
        new Lazy<DynamicType>(() => Implementation.NamesPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static NamesSupport Instance { get; } = ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<NamesSupport, Names>();
}
