// <auto-generated/>
// This file was generated by Wireloom from '05-shapes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;

namespace CorpusCollectionShapes;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Row"/>.
/// </summary>
public class RowSupport : TypeSupport<Row>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="RowSupport"/> class.
    /// </summary>
    public RowSupport() : base(
        new Implementation.RowPlugin(),
        new global::System.Lazy<DynamicType>(() => Implementation.RowPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the shared type-support instance for formatting, serialization, and dynamic-type utilities for this typedef.
    /// </summary>
    /// <remarks>The generated plugin and unmanaged type are runtime implementation details; application code should use this support class and the managed typedef.</remarks>
    public static RowSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<RowSupport, Row>();
}
