// <auto-generated/>
// This file was generated by Wireloom from '05-shapes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;
using System.Linq;

namespace CorpusCollectionShapes;

/// <summary>
/// Represents the <c>Names</c> IDL typedef declared in <c>05-shapes.idl</c>.
/// </summary>
public partial class Names : IEquatable<Names>
{
    /// <summary>
    /// Gets the sequence value represented by this typedef. Its maximum number of elements is <c>4</c>.
    /// </summary>
    [Bound(4)]
    public ISequence<string> Value { get; } = null!;

    /// <summary>
    /// Initializes an empty sequence typedef.
    /// </summary>
    public Names()
    {
        Value = new Sequence<string>();
    }

    /// <summary>
    /// Initializes the typedef with a sequence value.
    /// </summary>
    /// <param name="Value">The sequence value to store.</param>
    public Names(ISequence<string> Value)
    {
        this.Value = Value;
    }

    /// <summary>
    /// Initializes a copy of another sequence typedef.
    /// </summary>
    /// <param name="other">The typedef to copy.</param>
    public Names(Names? other)
    {
        if (other is null)
        {
            return;
        }

        Value = new Sequence<string>(other.Value);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Value.Count;
    }

    /// <summary>
    /// Determines whether this typedef has the same sequence values as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The typedef to compare.</param>
    public bool Equals(Names? other)
    {
        return other is not null
            && (ReferenceEquals(this, other) || Value.SequenceEqual(other.Value));
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Names);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this typedef.
    /// </summary>
    public override string ToString() => NamesSupport.Instance.ToString(this);
}
