// <auto-generated/>
// This file was generated by Wireloom from '05-shapes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using System;

namespace CorpusCollectionShapes.Implementation;

public struct RowsUnmanaged : INativeTopicType<Rows>
{
    private NativeSeq Value;

    /// <summary>
    /// Releases native resources held by this instance.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        Value.Destroy(optionalsOnly);
    }

    /// <summary>
    /// Copies native values into a managed typedef sample.
    /// </summary>
    /// <param name="sample">The managed typedef to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Rows sample, bool keysOnly = false)
    {
        Value.FromNative<Row, RowUnmanaged>((Sequence<Row>)sample.Value);
    }

    /// <summary>
    /// Initializes this native representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        Value.Initialize<Row, RowUnmanaged>(max: 2, absoluteMax: 2, allocateMemory: allocateMemory);
    }

    /// <summary>
    /// Copies a managed typedef sample into native storage.
    /// </summary>
    /// <param name="sample">The managed typedef to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Rows sample, bool keysOnly = false)
    {
        Value.ToNative<Row, RowUnmanaged>((Sequence<Row>)sample.Value);
    }
}
