// <auto-generated/>
// This file was generated by Wireloom from '05-shapes.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusCollectionShapes;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="BoundedLongs"/>.
/// </summary>
public class BoundedLongsSupport : TypeSupport<BoundedLongs>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="BoundedLongsSupport"/> class.
    /// </summary>
    public BoundedLongsSupport() : base(
        new Implementation.BoundedLongsPlugin(),
        new Lazy<DynamicType>(() => Implementation.BoundedLongsPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static BoundedLongsSupport Instance { get; } = ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<BoundedLongsSupport, BoundedLongs>();
}
