// <auto-generated/>
// This file was generated by Wireloom from '09-evolution-optional.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusOptionalEvolution.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Message"/>.
/// </summary>
internal class MessagePlugin : InterpretedTypePlugin<Message, MessageUnmanaged>
{
    internal MessagePlugin() : base("CorpusOptionalEvolution.Message", isKeyed: false, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Message"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new StructMember[]
        {
            new StructMember("requiredValue", dtf.GetPrimitiveType<int>(), id: 1),
            new StructMember("optionalValue", dtf.GetPrimitiveType<int>(), isOptional: true, id: 2),
            new StructMember("optionalText", dtf.CreateString(16), isOptional: true, id: 3)
        };

        var result = tsf.CreateTypeWithAccessInfo<MessageUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusOptionalEvolution::Message")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(1, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.String,
                defaultValue: new AnnotationParameterValue { StringValue = "" },
                minValue: null,
                maxValue: null,
                unit: null);
            result.SetMemberAnnotations(2, annotations);
        }

        return result;
    }
}
