// <auto-generated/>
// This file was generated by Wireloom from '09-evolution-optional.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusOptionalEvolution;

/// <summary>
/// Represents the <c>Message</c> DDS type declared in <c>09-evolution-optional.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Message : IEquatable<Message>
{
    /// <summary>
    /// Gets or sets the <c>requiredValue</c> member.
    /// </summary>
    public int requiredValue { get; set; }

    /// <summary>
    /// Gets or sets the <c>optionalValue</c> member. This member is optional.
    /// </summary>
    [Optional]
    public int? optionalValue { get; set; }

    /// <summary>
    /// Gets or sets the <c>optionalText</c> member. This member is optional. Its maximum length is <c>16</c>.
    /// </summary>
    [Optional]
    [Bound(16)]
    public string? optionalText { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Message"/> class.
    /// </summary>
    public Message()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Message"/> class with the supplied member values.
    /// </summary>
    /// <param name="requiredValue">The value for the <c>requiredValue</c> member.</param>
    /// <param name="optionalValue">The value for the <c>optionalValue</c> member.</param>
    /// <param name="optionalText">The value for the <c>optionalText</c> member.</param>
    public Message(int requiredValue, int? optionalValue, string? optionalText)
    {
        this.requiredValue = requiredValue;
        this.optionalValue = optionalValue;
        this.optionalText = optionalText;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Message"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Message(Message? other)
    {
        if (other is null)
        {
            return;
        }

        requiredValue = other.requiredValue;
        optionalValue = other.optionalValue;
        optionalText = other.optionalText;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(requiredValue);
        hash.Add(optionalValue);
        hash.Add(optionalText);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Message? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return requiredValue.Equals(other.requiredValue)
            && Equals(optionalValue, other.optionalValue)
            && Equals(optionalText, other.optionalText);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Message);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => MessageSupport.Instance.ToString(this);
}
