// <auto-generated/>
// This file was generated by Wireloom from '11-conditionals.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusConditionals;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="UndefBranch"/>.
/// </summary>
public class UndefBranchSupport : TypeSupport<UndefBranch>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="UndefBranchSupport"/> class.
    /// </summary>
    public UndefBranchSupport() : base(
        new Implementation.UndefBranchPlugin(),
        new Lazy<DynamicType>(() => Implementation.UndefBranchPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static UndefBranchSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<UndefBranchSupport, UndefBranch>();
}
