// <auto-generated/>
// This file was generated by Wireloom from '07-union-short.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusShortUnion;

/// <summary>
/// Represents the <c>Choice</c> DDS union declared in <c>07-union-short.idl</c>. Exactly one branch is selected by <see cref="Discriminator"/>.
/// </summary>
public partial class Choice : IEquatable<Choice>
{
    private int _negative;
    private string _text = string.Empty;
    private bool _other;

    /// <summary>
    /// Gets the discriminator that selects the active DDS union branch.
    /// </summary>
    public short Discriminator { get; private set; }

    /// <summary>
    /// Gets the discriminator value used to initialize this union.
    /// </summary>
    public const short DefaultDiscriminator = 0;

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>-1</c>.
    /// </summary>
    public int negative
    {
        get
        {
            if (Discriminator != -1)
            {
                throw new InvalidOperationException("negative not selected");
            }
            return _negative;
        }

        set
        {
            _negative = value;
            Discriminator = -1;
        }
    }

    /// <summary>
    /// Gets or sets the union branch selected when <see cref="Discriminator"/> is one of: <c>2</c>.
    /// </summary>
    [Bound(255)]
    public string text
    {
        get
        {
            if (Discriminator != 2)
            {
                throw new InvalidOperationException("text not selected");
            }
            return _text;
        }

        set
        {
            _text = value;
            Discriminator = 2;
        }
    }

    /// <summary>
    /// Gets or sets the default union branch, selected when the discriminator does not match an explicit case.
    /// </summary>
    public bool other
    {
        get
        {
            if (Discriminator == -1 || Discriminator == 2)
            {
                throw new InvalidOperationException("other not selected");
            }
            return _other;
        }

        set
        {
            _other = value;
            Discriminator = 0;
        }
    }

    /// <summary>
    /// Initializes a new union with its RTI default discriminator.
    /// </summary>
    public Choice()
    {
        Discriminator = DefaultDiscriminator;
    }

    /// <summary>
    /// Initializes a copy of another <see cref="Choice"/> union.
    /// </summary>
    /// <param name="other">The union to copy.</param>
    public Choice(Choice? other)
    {
        if (other is null)
        {
            return;
        }

        Discriminator = other.Discriminator;

        switch (Discriminator)
        {
            case -1:
                this._negative = other.negative;
                break;
            case 2:
                this._text = other.text;
                break;
            default:
                this._other = other.other;
                break;
        }
    }

    /// <summary>
    /// Sets the default branch with an explicit discriminator value.
    /// </summary>
    /// <param name="value">The value for the default branch.</param>
    /// <param name="discriminator">A discriminator value that does not select an explicit branch.</param>
    public void Setother(bool value, short discriminator)
    {
        if (discriminator == -1 || discriminator == 2)
        {
            throw new ArgumentException("Invalid discriminator value for other", nameof(discriminator));
        }
        _other = value;
        Discriminator = discriminator;
    }

    /// <summary>
    /// Gets the currently active union-branch value.
    /// </summary>
    /// <returns>The value of the branch selected by <see cref="Discriminator"/>.</returns>
    public object Get()
    {
        switch (Discriminator)
        {
            case -1:
                return negative;
            case 2:
                return text;
            default:
                return other;
        }
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        switch (Discriminator)
        {
            case -1:
                return HashCode.Combine(Discriminator, negative);
            case 2:
                return HashCode.Combine(Discriminator, text);
            default:
                return HashCode.Combine(Discriminator, other);
        }
    }

    /// <summary>
    /// Determines whether this union has the same discriminator and active branch value as <paramref name="other"/>.
    /// </summary>
    /// <param name="other">The union to compare.</param>
    /// <returns><see langword="true"/> when both unions select equal values; otherwise <see langword="false"/>.</returns>
    public bool Equals(Choice? other)
    {
        if (other is null || Discriminator != other.Discriminator)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        switch (Discriminator)
        {
            case -1:
                return negative.Equals(other.negative);
            case 2:
                return text.Equals(other.text);
            default:
                return other.Equals(other.other);
        }
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Choice);

    /// <summary>
    /// Returns the RTI Connext DDS representation of this union.
    /// </summary>
    public override string ToString() => ChoiceSupport.Instance.ToString(this);
}
