// <auto-generated/>
// This file was generated by Wireloom from '08-key-nested.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

namespace CorpusNestedKeys;

/// <summary>
/// Represents the <c>Outer</c> DDS type declared in <c>08-key-nested.idl</c>. Its key members identify a DDS instance across samples; they do not determine whether two complete samples are equal. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Outer : global::System.IEquatable<Outer>
{
    /// <summary>
    /// Gets or sets the <c>identity</c> member. This member forms part of the DDS instance key.
    /// </summary>
    [Key]
    public Inner identity { get; set; } = new Inner();

    /// <summary>
    /// Gets or sets the <c>payload</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>.
    /// </summary>
    public int payload { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Outer"/> class.
    /// </summary>
    /// <remarks>nested aggregate members start as new instances.</remarks>
    public Outer()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Outer"/> class with the supplied member values.
    /// </summary>
    /// <param name="identity">The value for the <c>identity</c> member.</param>
    /// <param name="payload">The value for the <c>payload</c> member.</param>
    /// <remarks>The constructor stores supplied reference-type member values as provided. It does not clone their arrays, sequences, or nested objects.</remarks>
    public Outer(Inner identity, int payload)
    {
        this.identity = identity;
        this.payload = payload;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Outer"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Outer();
    /// var copy = new Outer(original);
    /// </code>
    /// </example>
    public Outer(Outer? other)
    {
        if (other is null)
        {
            return;
        }

        identity = new Inner(other.identity);
        payload = other.payload;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(identity);
        hash.Add(payload);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Outer? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return identity.Equals(other.identity)
            && payload.Equals(other.payload);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Outer);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => OuterSupport.Instance.ToString(this);
}
