// <auto-generated/>
// This file was generated by Wireloom from '08-key-nested.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

namespace CorpusNestedKeys;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="Outer"/>.
/// </summary>
public class OuterSupport : TypeSupport<Outer>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="OuterSupport"/> class.
    /// </summary>
    public OuterSupport() : base(
        new Implementation.OuterPlugin(),
        new Lazy<DynamicType>(() => Implementation.OuterPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static OuterSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<OuterSupport, Outer>();
}
