// <auto-generated/>
// This file was generated by Wireloom from '08-key-nested.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusNestedKeys;

/// <summary>
/// Represents the <c>Outer</c> DDS type declared in <c>08-key-nested.idl</c>. Its key members form the DDS instance key. It is marked as <c>extensible</c>.
/// </summary>
public partial class Outer : IEquatable<Outer>
{
    /// <summary>
    /// Gets or sets the <c>identity</c> member. This member forms part of the DDS instance key.
    /// </summary>
    [Key]
    public Inner identity { get; set; } = new Inner();

    /// <summary>
    /// Gets or sets the <c>payload</c> member.
    /// </summary>
    public int payload { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Outer"/> class.
    /// </summary>
    public Outer()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Outer"/> class with the supplied member values.
    /// </summary>
    /// <param name="identity">The value for the <c>identity</c> member.</param>
    /// <param name="payload">The value for the <c>payload</c> member.</param>
    public Outer(Inner identity, int payload)
    {
        this.identity = identity;
        this.payload = payload;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Outer"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Outer(Outer? other)
    {
        if (other is null)
        {
            return;
        }

        identity = new Inner(other.identity);
        payload = other.payload;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(identity);
        hash.Add(payload);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Outer? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return identity.Equals(other.identity)
            && payload.Equals(other.payload);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Outer);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => OuterSupport.Instance.ToString(this);
}
