// <auto-generated/>
// This file was generated by Wireloom from '08-key-nested.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

namespace CorpusNestedKeys;

/// <summary>
/// Represents the <c>Inner</c> DDS type declared in <c>08-key-nested.idl</c>. Its key members form the DDS instance key. It is marked as <c>extensible</c>.
/// </summary>
public partial class Inner : IEquatable<Inner>
{
    /// <summary>
    /// Gets or sets the <c>code</c> member. This member forms part of the DDS instance key.
    /// </summary>
    [Key]
    public int code { get; set; }

    /// <summary>
    /// Gets or sets the <c>revision</c> member.
    /// </summary>
    public int revision { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Inner"/> class.
    /// </summary>
    public Inner()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Inner"/> class with the supplied member values.
    /// </summary>
    /// <param name="code">The value for the <c>code</c> member.</param>
    /// <param name="revision">The value for the <c>revision</c> member.</param>
    public Inner(int code, int revision)
    {
        this.code = code;
        this.revision = revision;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Inner"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Inner(Inner? other)
    {
        if (other is null)
        {
            return;
        }

        code = other.code;
        revision = other.revision;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(code);
        hash.Add(revision);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Inner? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return code.Equals(other.code)
            && revision.Equals(other.revision);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Inner);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => InnerSupport.Instance.ToString(this);
}
