// <auto-generated/>
// This file was generated by Wireloom from '07-union-boolean.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;

namespace CorpusBooleanUnion.Implementation;

/// <summary>
/// Provides the RTI native representation for <see cref="Choice"/>.
/// </summary>
public struct ChoiceUnmanaged : INativeTopicType<Choice>
{
    private byte _discriminator;

    private int enabled;
    private NativeString disabled;

    /// <summary>
    /// Releases native resources held by this union.
    /// </summary>
    /// <param name="optionalsOnly">Indicates whether only optional members should be released.</param>
    public void Destroy(bool optionalsOnly)
    {
        if (optionalsOnly)
        {
            return;
        }

        disabled.Destroy();
    }

    /// <summary>
    /// Copies the active native union branch into a managed sample.
    /// </summary>
    /// <param name="sample">The managed sample to populate.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void FromNative(Choice sample, bool keysOnly = false)
    {
        switch (global::System.Convert.ToBoolean(_discriminator))
        {
            case true:
                sample.enabled = enabled;
                break;

            case false:
                sample.disabled = disabled.FromNative();
                break;
        }
    }

    /// <summary>
    /// Initializes this native union representation to its IDL default values.
    /// </summary>
    /// <param name="allocatePointers">Whether pointer members should be allocated.</param>
    /// <param name="allocateMemory">Whether native memory should be allocated.</param>
    public void Initialize(bool allocatePointers = true, bool allocateMemory = true)
    {
        _discriminator = global::System.Convert.ToByte(Choice.DefaultDiscriminator);

        enabled = 0;

        disabled.Initialize(size: 255, allocateMemory: allocateMemory);
    }

    /// <summary>
    /// Copies the active managed union branch into native storage.
    /// </summary>
    /// <param name="sample">The managed sample to copy.</param>
    /// <param name="keysOnly">Whether to copy only key members.</param>
    public void ToNative(Choice sample, bool keysOnly = false)
    {
        _discriminator = global::System.Convert.ToByte(sample.Discriminator);

        switch (global::System.Convert.ToBoolean(_discriminator))
        {
            case true:
                enabled = sample.enabled;
                break;

            case false:
                disabled.ToNative(sample.disabled, 255);
                break;
        }
    }
}
