// <auto-generated/>
// This file was generated by Wireloom from '10-annotations-rti.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Omg.Types.Dynamic;
using Rti.Dds.Core;
using Rti.Dds.NativeInterface.TypePlugin;
using Rti.Types;
using Rti.Types.Dynamic;

namespace CorpusRtiAnnotations.Implementation;

/// <summary>
/// Provides the RTI interpreted type plugin for <see cref="Sample"/>.
/// </summary>
internal class SamplePlugin : InterpretedTypePlugin<Sample, SampleUnmanaged>
{
    /// <summary>
    /// Initializes the RTI plugin for <see cref="Sample"/>.
    /// </summary>
    internal SamplePlugin() : base("CorpusRtiAnnotations.Sample", isKeyed: true, CreateDynamicType(isPublic: false))
    {
    }

    /// <summary>
    /// Creates the RTI dynamic type description for <see cref="Sample"/>.
    /// </summary>
    /// <param name="isPublic">Whether the resulting dynamic type is publicly visible to RTI.</param>
    /// <returns>The RTI dynamic type description.</returns>
    public static DynamicType CreateDynamicType(bool isPublic = true)
    {
        var dtf = ServiceEnvironment.Instance.Internal.GetTypeFactory(isPublic);
        var tsf = ServiceEnvironment.Instance.Internal.TypeSupportFactory;

        var members = new[]
        {
            new StructMember("id", dtf.GetPrimitiveType<int>(), isKey: true, id: 0),
            new StructMember("value", dtf.GetPrimitiveType<int>(), id: 1),
            new StructMember("text", dtf.CreateString(16), id: 2),
            new StructMember("externalText", dtf.CreateString(16), id: 3)
        };

        var result = tsf.CreateTypeWithAccessInfo<SampleUnmanaged>(
            dtf.BuildStruct()
                .WithExtensibility(ExtensibilityKind.Extensible)
                .WithName("CorpusRtiAnnotations::Sample")
                .AddMembers(members));

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = int.MinValue },
                maxValue: new AnnotationParameterValue { Int32Value = int.MaxValue },
                unit: null);
            result.SetMemberAnnotations(0, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.Int32,
                defaultValue: new AnnotationParameterValue { Int32Value = 0 },
                minValue: new AnnotationParameterValue { Int32Value = -32 },
                maxValue: new AnnotationParameterValue { Int32Value = 31 },
                unit: "meters");
            result.SetMemberAnnotations(1, annotations);
        }

        {
            var annotations = new Annotations(
                TypeKind.String,
                defaultValue: new AnnotationParameterValue { StringValue = "" },
                minValue: null,
                maxValue: null,
                unit: null);
            result.SetMemberAnnotations(2, annotations);
        }

        return result;
    }
}
