// <auto-generated/>
// This file was generated by Wireloom from '12-macro-recursion.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

namespace CorpusNegativeMacroRecursion;

/// <summary>
/// Represents the <c>Sample</c> DDS type declared in <c>12-macro-recursion.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Sample : global::System.IEquatable<Sample>
{
    /// <summary>
    /// Gets or sets the <c>CORPUS_A</c> member. Representable values are in the inclusive range <c>int.MinValue</c> through <c>int.MaxValue</c>.
    /// </summary>
    public int CORPUS_A { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class.
    /// </summary>
    public Sample()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Sample"/> class with the supplied member values.
    /// </summary>
    /// <param name="CORPUS_A">The value for the <c>CORPUS_A</c> member.</param>
    public Sample(int CORPUS_A)
    {
        this.CORPUS_A = CORPUS_A;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Sample"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Sample();
    /// var copy = new Sample(original);
    /// </code>
    /// </example>
    public Sample(Sample? other)
    {
        if (other is null)
        {
            return;
        }

        CORPUS_A = other.CORPUS_A;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(CORPUS_A);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Sample? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return CORPUS_A.Equals(other.CORPUS_A);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Sample);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SampleSupport.Instance.ToString(this);
}
