// <auto-generated/>
// This file was generated by Wireloom from '02-multiple.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Rti.Dds.Core;
using Rti.Dds.Topics;
using Rti.Types.Dynamic;
using System;

/// <summary>
/// Provides RTI Connext DDS type support for <see cref="First"/>.
/// </summary>
public class FirstSupport : TypeSupport<First>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="FirstSupport"/> class.
    /// </summary>
    public FirstSupport() : base(
        new Implementation.FirstPlugin(),
        new Lazy<DynamicType>(() => Implementation.FirstPlugin.CreateDynamicType(isPublic: true)))
    {
    }

    /// <summary>
    /// Gets the cached RTI Connext DDS type-support instance.
    /// </summary>
    public static FirstSupport Instance { get; } =
        ServiceEnvironment.Instance.Internal.TypeSupportFactory.CreateTypeSupport<FirstSupport, First>();
}
