// <auto-generated/>
// This file was generated by Wireloom from '02-multiple.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;

/// <summary>
/// Represents the <c>Second</c> DDS type declared in <c>02-multiple.idl</c>. It is marked as <c>extensible</c>. New members may be appended while preserving the existing member order for compatible type evolution.
/// </summary>
public partial class Second : global::System.IEquatable<Second>
{
    /// <summary>
    /// Gets or sets the <c>name</c> member. Its maximum length is <c>255</c> characters.
    /// </summary>
    /// <seealso href="https://community.rti.com/static/documentation/connext-dds/7.7.0/doc/manuals/connext_dds_professional/users_manual/users_manual/Strings_and_Wide_Strings.htm">RTI Connext 7.7.0 string and wide-string bounds</seealso>
    /// <remarks>This unbounded narrow IDL string has an effective limit of 255 characters. RTI encodes narrow IDL strings as UTF-8 by default. The generated C# property does not enforce the effective limit when assigned.</remarks>
    [Bound(255)]
    public string name { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Second"/> class.
    /// </summary>
    public Second()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Second"/> class with the supplied member values.
    /// </summary>
    /// <param name="name">The value for the <c>name</c> member.</param>
    public Second(string name)
    {
        this.name = name;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Second"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    /// <remarks>Arrays and sequences are copied into new containers, and nested aggregate members are copied through their generated copy constructors. When <paramref name="other"/> is null, the constructor returns without copying; property initializers remain in effect, but values created only by the parameterless constructor are not initialized.</remarks>
    /// <example>
    /// <code>
    /// var original = new Second();
    /// var copy = new Second(original);
    /// </code>
    /// </example>
    public Second(Second? other)
    {
        if (other is null)
        {
            return;
        }

        name = other.name;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(name);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Second? other)
    {
        if (other is null)
        {
            return false;
        }

        if (global::System.Object.ReferenceEquals(this, other))
        {
            return true;
        }

        return name.Equals(other.name);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Second);

    /// <summary>
    /// Formats this sample as readable text.
    /// </summary>
    /// <returns>A readable string formatted by the type-support instance.</returns>
    public override string ToString() => SecondSupport.Instance.ToString(this);
}
