// <auto-generated/>
// This file was generated by Wireloom from '02-multiple.idl'.
// Do not modify it directly; update the IDL source and rebuild.
// It requires the RTI Connext DDS .NET runtime.
#nullable enable

using Omg.Types;
using Rti.Types;
using System;

/// <summary>
/// Represents the <c>Second</c> DDS type declared in <c>02-multiple.idl</c>. It is marked as <c>extensible</c>.
/// </summary>
public partial class Second : IEquatable<Second>
{
    /// <summary>
    /// Gets or sets the <c>name</c> member. Its maximum length is <c>255</c>.
    /// </summary>
    [Bound(255)]
    public string name { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="Second"/> class.
    /// </summary>
    public Second()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Second"/> class with the supplied member values.
    /// </summary>
    /// <param name="name">The value for the <c>name</c> member.</param>
    public Second(string name)
    {
        this.name = name;
    }

    /// <summary>
    /// Initializes a copy of the specified <see cref="Second"/> instance.
    /// </summary>
    /// <param name="other">The instance to copy, or <see langword="null"/>.</param>
    public Second(Second? other)
    {
        if (other is null)
        {
            return;
        }

        name = other.name;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();

        hash.Add(name);

        return hash.ToHashCode();
    }

    /// <summary>
    /// Determines whether this instance and <paramref name="other"/> have identical member values.
    /// </summary>
    /// <param name="other">The instance to compare, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the member values are equal; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Second? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return name.Equals(other.name);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as Second);

    /// <summary>
    /// Returns the RTI Connext DDS type-support representation of this sample.
    /// </summary>
    /// <returns>The RTI Connext DDS representation of this sample.</returns>
    public override string ToString() => SecondSupport.Instance.ToString(this);
}
